export interface FrameworkDockerSmokeFixture {
  fixture: string;
  matrixIds: string;
  method: "auto";
  port: number;
  healthPath: string;
  expectedBuildStrategy: "static-artifact" | "workspace-commands";
  expectedDockerfile: "Dockerfile.appaloft" | "Dockerfile.appaloft-static";
  expectedGeneratedLog: string;
  expectedPlanner: string;
  expectedResourceKind: "application" | "static-site";
  expectedRuntimeText?: string;
  install?: string;
  build?: string;
  start?: string;
}

export const frameworkDockerSmokeFixtures: FrameworkDockerSmokeFixture[] = [
  {
    fixture: "vite-spa",
    matrixIds:
      "ZSSH-CATALOG-002,WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "vite-static",
    expectedResourceKind: "application",
  },
  {
    fixture: "next-static-export",
    matrixIds: "WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "nextjs-static",
    expectedResourceKind: "application",
  },
  {
    fixture: "react-spa",
    matrixIds: "WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "react-static",
    expectedResourceKind: "application",
  },
  {
    fixture: "vue-spa",
    matrixIds: "WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "vue-static",
    expectedResourceKind: "application",
  },
  {
    fixture: "svelte-spa",
    matrixIds: "WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "svelte-static",
    expectedResourceKind: "application",
  },
  {
    fixture: "solid-spa",
    matrixIds: "WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "solid-static",
    expectedResourceKind: "application",
  },
  {
    fixture: "angular-spa",
    matrixIds: "WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "angular-static",
    expectedResourceKind: "application",
  },
  {
    fixture: "astro-static",
    matrixIds:
      "ZSSH-CATALOG-003,WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "astro-static",
    expectedResourceKind: "application",
    expectedRuntimeText: "Astro fixture ready",
  },
  {
    fixture: "nuxt-generate",
    matrixIds:
      "ZSSH-CATALOG-004,WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "nuxt-static",
    expectedResourceKind: "application",
    expectedRuntimeText: "Nuxt fixture ready",
  },
  {
    fixture: "sveltekit-static",
    matrixIds:
      "ZSSH-CATALOG-005,WF-PLAN-SMOKE-001,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 80,
    healthPath: "/",
    expectedBuildStrategy: "static-artifact",
    expectedDockerfile: "Dockerfile.appaloft-static",
    expectedGeneratedLog: "Generated static site Dockerfile",
    expectedPlanner: "sveltekit-static",
    expectedResourceKind: "application",
    expectedRuntimeText: "SvelteKit static fixture ready",
  },
  {
    fixture: "next-ssr",
    matrixIds:
      "ZSSH-CATALOG-001,WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "nextjs",
    expectedResourceKind: "application",
    expectedRuntimeText: "Next SSR fixture ready",
    install: "corepack enable && rm -f pnpm-lock.yaml && pnpm install",
    build: "corepack pnpm build",
    start: "corepack pnpm exec next start -H 0.0.0.0 -p 3000",
  },
  {
    fixture: "next-standalone",
    matrixIds: "WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "nextjs",
    expectedResourceKind: "application",
  },
  {
    fixture: "remix-ssr",
    matrixIds:
      "ZSSH-CATALOG-006,WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "remix",
    expectedResourceKind: "application",
    expectedRuntimeText: "Remix fixture ready",
  },
  {
    fixture: "express-server",
    matrixIds: "WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "node",
    expectedResourceKind: "application",
    expectedRuntimeText: "Express fixture ready",
  },
  {
    fixture: "fastify-server",
    matrixIds: "WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "node",
    expectedResourceKind: "application",
    expectedRuntimeText: "ok",
  },
  {
    fixture: "nestjs-server",
    matrixIds: "WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "node",
    expectedResourceKind: "application",
    expectedRuntimeText: "NestJS fixture ready",
  },
  {
    fixture: "hono-server",
    matrixIds: "WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "node",
    expectedResourceKind: "application",
    expectedRuntimeText: "Hono fixture ready",
  },
  {
    fixture: "koa-server",
    matrixIds: "WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "node",
    expectedResourceKind: "application",
    expectedRuntimeText: "Koa fixture ready",
  },
  {
    fixture: "generic-node-server",
    matrixIds:
      "ZSSH-CATALOG-010,WF-PLAN-SMOKE-002,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "node",
    expectedResourceKind: "application",
    expectedRuntimeText: "Generic Node fixture ready",
  },
  {
    fixture: "generic-asgi-uv",
    matrixIds:
      "ZSSH-CATALOG-011,WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "generic-asgi",
    expectedResourceKind: "application",
    expectedRuntimeText: "generic asgi",
  },
  {
    fixture: "generic-wsgi-pip",
    matrixIds: "WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "generic-wsgi",
    expectedResourceKind: "application",
    expectedRuntimeText: "generic wsgi",
  },
  {
    fixture: "python-poetry-web",
    matrixIds: "WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "flask",
    expectedResourceKind: "application",
    expectedRuntimeText: "poetry flask",
  },
  {
    fixture: "fastapi-uv",
    matrixIds:
      "ZSSH-CATALOG-007,WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "fastapi",
    expectedResourceKind: "application",
    expectedRuntimeText: "FastAPI fixture ready",
  },
  {
    fixture: "django-pip",
    matrixIds:
      "ZSSH-CATALOG-008,WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "django",
    expectedResourceKind: "application",
    expectedRuntimeText: "Django fixture ready",
  },
  {
    fixture: "flask-pip",
    matrixIds:
      "ZSSH-CATALOG-009,WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "flask",
    expectedResourceKind: "application",
    expectedRuntimeText: "Flask fixture ready",
  },
  {
    fixture: "jvm-explicit-start",
    matrixIds: "WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 3000,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "java",
    expectedResourceKind: "application",
    expectedRuntimeText: "JVM explicit start fixture ready",
    build: "true",
    start: "java Server.java 3000",
  },
  {
    fixture: "generic-java-jar",
    matrixIds:
      "ZSSH-CATALOG-012,WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 8080,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "java",
    expectedResourceKind: "application",
    expectedRuntimeText: "Generic Java jar fixture ready",
  },
  {
    fixture: "spring-boot-maven-wrapper",
    matrixIds: "WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 8080,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "spring-boot",
    expectedResourceKind: "application",
    expectedRuntimeText: "Spring Boot Maven wrapper fixture ready",
  },
  {
    fixture: "spring-boot-maven",
    matrixIds: "WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 8080,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "spring-boot",
    expectedResourceKind: "application",
    expectedRuntimeText: "Spring Boot Maven fixture ready",
  },
  {
    fixture: "quarkus-maven",
    matrixIds:
      "ZSSH-CATALOG-017,WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 8080,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "quarkus",
    expectedResourceKind: "application",
    expectedRuntimeText: "Quarkus fixture ready",
  },
  {
    fixture: "spring-boot-gradle-wrapper",
    matrixIds: "WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 8080,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "spring-boot",
    expectedResourceKind: "application",
    expectedRuntimeText: "Spring Boot Gradle fixture ready",
  },
  {
    fixture: "spring-boot-gradle-kts",
    matrixIds: "WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 8080,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "spring-boot",
    expectedResourceKind: "application",
    expectedRuntimeText: "Spring Boot Gradle Kotlin fixture ready",
  },
  {
    fixture: "python-explicit-start",
    matrixIds:
      "ZSSH-CATALOG-016,WF-PLAN-SMOKE-003,WF-PLAN-SMOKE-005,WF-PLAN-SMOKE-006,QUICK-DEPLOY-ENTRY-015",
    method: "auto",
    port: 4317,
    healthPath: "/",
    expectedBuildStrategy: "workspace-commands",
    expectedDockerfile: "Dockerfile.appaloft",
    expectedGeneratedLog: "Generated workspace Dockerfile",
    expectedPlanner: "generic-python",
    expectedResourceKind: "application",
    expectedRuntimeText: "explicit start",
    install: "pip install --no-cache-dir --retries 10 --timeout 120 -r requirements.txt",
    start: "python -m waitress --listen=0.0.0.0:4317 service:application",
  },
];
