import { dirname } from "node:path";
import { ash } from "@appaloft/ash";

import type { DockerEnvironmentVariableInput } from "./runtime-commands";

function assertShellIdentifier(name: string): void {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    throw new Error(`Unsupported runtime environment variable name: ${name}`);
  }
}

export function renderRuntimeEnvironmentShellFile(input: {
  variables: readonly DockerEnvironmentVariableInput[];
}): string {
  const seen = new Set<string>();
  const lines = [
    "# Generated by Appaloft. Contains deployment runtime environment.",
  ];

  for (const variable of [...input.variables].sort((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    if (seen.has(variable.name)) {
      continue;
    }
    assertShellIdentifier(variable.name);
    seen.add(variable.name);
    lines.push(`export ${variable.name}=${ash.quote(variable.value)}`);
  }

  return `${lines.join("\n")}\n`;
}

export function renderRemotePrivateTextFileCommand(input: {
  path: string;
  contents: string;
}): { command: string; redactions: string[] } {
  const encoded = Buffer.from(input.contents, "utf8").toString("base64");
  const command = [
    `mkdir -p ${ash.quote(dirname(input.path))}`,
    `tmp="$(mktemp ${ash.quote(`${input.path}.tmp.XXXXXX`)})"`,
    `trap 'rm -f "$tmp"' 0`,
    `printf %s ${ash.quote(encoded)} | base64 -d > "$tmp"`,
    'chmod 600 "$tmp"',
    `mv "$tmp" ${ash.quote(input.path)}`,
    "trap - 0",
  ].join(" && ");

  return {
    command,
    redactions: [input.contents, encoded],
  };
}

export function withRemoteRuntimeEnvironmentFile(input: {
  envFile: string;
  command: string;
}): string {
  return `{ . ${ash.quote(input.envFile)}; } && {\n${input.command}\n}`;
}

export function withOptionalRemoteRuntimeEnvironmentFile(input: {
  envFile: string;
  command: string;
}): string {
  return `{ if [ -f ${ash.quote(input.envFile)} ]; then . ${ash.quote(
    input.envFile,
  )}; fi; } && {\n${input.command}\n}`;
}
