// Generated by scripts/sync-bun-version.ts. Update /.bun-version, then run bun run bun:version:sync.
export const pinnedBunVersion = "1.3.14";
export const pinnedBunAlpineImage = `oven/bun:${pinnedBunVersion}-alpine`;
