export const appaloftPortableDesignTokens = {
  color: {
    accent: "#edf3ff",
    accentForeground: "#2857c8",
    background: "#ffffff",
    border: "#cbd6e5",
    card: "#ffffff",
    control: "#aebdd1",
    divider: "#cbd6e5",
    foreground: "#12213a",
    muted: "#f5f7fa",
    mutedForeground: "#586a82",
    primary: "#4e84ff",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#273951",
    surface: "#ffffff",
    surfaceOverlay: "#ffffff",
    surfaceSelected: "#edf3ff",
    surfaceSubtle: "#f5f7fa",
  },
  fontFamily: {
    mono: [
      "IBM Plex Mono",
      "SFMono-Regular",
      "SF Mono",
      "Menlo",
      "Monaco",
      "Consolas",
      "Liberation Mono",
      "monospace",
    ],
    sans: ["IBM Plex Sans", "ui-sans-serif", "system-ui", "sans-serif"],
    serif: ["Fraunces", "ui-serif", "Georgia", "serif"],
  },
  radius: {
    sm: "4px",
    md: "6px",
    lg: "8px",
  },
  shadow: {
    sm: "0 1px 2px 0 hsl(214 48% 19% / 6%), 0 1px 1px -1px hsl(214 48% 19% / 6%)",
  },
} as const;
