import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const bunVersionPath = resolve(root, ".bun-version");
const packageJsonPath = resolve(root, "package.json");
const runtimeHelperPath = resolve(
  root,
  "packages",
  "adapters",
  "runtime",
  "src",
  "workspace-planners",
  "bun.ts",
);

const checkOnly = Bun.argv.includes("--check");
const bunVersion = (await Bun.file(bunVersionPath).text()).trim();
const packageJson = (await Bun.file(packageJsonPath).json()) as Record<string, unknown>;

if (!/^\d+\.\d+\.\d+$/u.test(bunVersion)) {
  throw new Error(`Expected .bun-version to contain an exact semantic version, got: ${bunVersion}`);
}

const nextRuntimeHelper = `// Generated by scripts/sync-bun-version.ts. Update /.bun-version, then run bun run bun:version:sync.
export const pinnedBunVersion = "${bunVersion}";
export const pinnedBunAlpineImage = \`oven/bun:\${pinnedBunVersion}-alpine\`;
`;

const currentRuntimeHelper = await Bun.file(runtimeHelperPath).text();
const nextPackageManager = `bun@${bunVersion}`;
const currentPackageManager =
  typeof packageJson.packageManager === "string" ? packageJson.packageManager : undefined;

const packageManagerNeedsUpdate = currentPackageManager !== nextPackageManager;
const runtimeHelperNeedsUpdate = currentRuntimeHelper !== nextRuntimeHelper;

if (!packageManagerNeedsUpdate && !runtimeHelperNeedsUpdate) {
  console.log(`Bun version sync is up to date at ${bunVersion}.`);
  process.exit(0);
}

if (checkOnly) {
  throw new Error(
    `Bun version sync is stale. Update ${bunVersionPath} and run: bun run bun:version:sync`,
  );
}

if (packageManagerNeedsUpdate) {
  const nextPackageJson = {
    ...packageJson,
    packageManager: nextPackageManager,
  };
  await Bun.write(packageJsonPath, `${JSON.stringify(nextPackageJson, null, 2)}\n`);
}

if (runtimeHelperNeedsUpdate) {
  await Bun.write(runtimeHelperPath, nextRuntimeHelper);
}

console.log(`Synchronized Bun runtime image helpers to ${bunVersion}.`);
