import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const bunVersionPath = resolve(root, ".bun-version");
const runtimeHelperPath = resolve(
  root,
  "packages",
  "adapters",
  "runtime",
  "src",
  "workspace-planners",
  "bun.ts",
);

const checkOnly = Bun.argv.includes("--check");
const bunVersion = (await Bun.file(bunVersionPath).text()).trim();

if (!/^\d+\.\d+\.\d+$/u.test(bunVersion)) {
  throw new Error(`Expected .bun-version to contain an exact semantic version, got: ${bunVersion}`);
}

const nextRuntimeHelper = `// Generated by scripts/sync-bun-version.ts. Update /.bun-version, then run bun run bun:version:sync.
export const pinnedBunVersion = "${bunVersion}";
export const pinnedBunAlpineImage = \`oven/bun:\${pinnedBunVersion}-alpine\`;
`;

const currentRuntimeHelper = await Bun.file(runtimeHelperPath).text();

if (currentRuntimeHelper === nextRuntimeHelper) {
  console.log(`Bun version sync is up to date at ${bunVersion}.`);
  process.exit(0);
}

if (checkOnly) {
  throw new Error(
    `Bun version sync is stale. Update ${bunVersionPath} and run: bun run bun:version:sync`,
  );
}

await Bun.write(runtimeHelperPath, nextRuntimeHelper);
console.log(`Synchronized Bun runtime image helpers to ${bunVersion}.`);
