<script lang="ts">
  import { Button } from "@appaloft/ui/button";
  import { Archive, GitBranch, LoaderCircle, Plus, RefreshCw, Save, ShieldAlert, TriangleAlert } from "@lucide/svelte";
  import { dashboardClient } from "$lib/data-client";
  import { dashboardI18n as i18n } from "$lib/i18n.svelte";

  let { projectId }: { projectId: string } = $props();
  type Project = Awaited<ReturnType<typeof dashboardClient.projects.show>>;
  type DeleteCheck = Awaited<ReturnType<typeof dashboardClient.projects.deleteCheck>>;
  type Environments = Awaited<ReturnType<typeof dashboardClient.environments.list>>;
  let project = $state<Project>(); let check = $state<DeleteCheck>(); let environments = $state<Environments>(); let name = $state(""); let description = $state(""); let environmentName = $state(""); let environmentKind = $state<"development" | "test" | "staging" | "production" | "custom">("development"); let creatingEnvironment = $state(false); let environmentFormOpen = $state(false);
  let loading = $state(true); let error = $state(false); let saving = $state(false); let actioning = $state(false); let message = $state(""); let actionError = $state("");
  const t = (en: string, zh: string) => i18n.locale === "zh-CN" ? zh : en;

  async function load(): Promise<void> { loading = true; error = false; try { [project, check, environments] = await Promise.all([dashboardClient.projects.show({ projectId }), dashboardClient.projects.deleteCheck({ projectId }), dashboardClient.environments.list({ projectId, limit: 100 })]); name = project.name; description = project.description ?? ""; } catch { project = undefined; check = undefined; environments = undefined; error = true; } finally { loading = false; } }
  async function save(event: SubmitEvent): Promise<void> { event.preventDefault(); if (!project) return; saving = true; message = ""; actionError = ""; try { if (name.trim() !== project.name) await dashboardClient.projects.rename({ projectId, name: name.trim() }); if (description.trim() !== (project.description ?? "")) await dashboardClient.projects.setDescription({ projectId, description: description.trim() || undefined }); await load(); message = t("Project settings saved.", "Project 设置已保存。"); } catch { actionError = t("Project settings could not be saved.", "无法保存 Project 设置。"); } finally { saving = false; } }
  async function toggleLifecycle(): Promise<void> { if (!project) return; actioning = true; message = ""; actionError = ""; try { if (project.lifecycleStatus === "active") await dashboardClient.projects.archive({ projectId, reason: "Archived from Dashboard settings" }); else await dashboardClient.projects.restore({ projectId }); await load(); message = project?.lifecycleStatus === "archived" ? t("Project archived.", "Project 已归档。") : t("Project restored.", "Project 已恢复。"); } catch { actionError = t("Lifecycle action failed.", "生命周期操作失败。"); } finally { actioning = false; } }
  async function createEnvironment(event: SubmitEvent): Promise<void> { event.preventDefault(); creatingEnvironment = true; actionError = ""; try { await dashboardClient.environments.create({ projectId, name: environmentName.trim(), kind: environmentKind }); environmentName = ""; environmentFormOpen = false; await load(); message = t("Environment created.", "Environment 已创建。"); } catch { actionError = t("Environment could not be created.", "无法创建 Environment。"); } finally { creatingEnvironment = false; } }
  $effect(() => { projectId; void load(); });
</script>

<section data-project-settings class="mt-8 grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]">
  {#if loading}<div class="col-span-full grid min-h-64 place-items-center rounded-[16px] border border-divider bg-surface"><LoaderCircle class="size-6 animate-spin text-primary" /></div>
  {:else if error || !project}<div class="col-span-full rounded-[16px] border border-destructive/25 bg-destructive/[0.04] p-8 text-center"><TriangleAlert class="mx-auto size-6 text-destructive" /><h2 class="mt-4 font-semibold">{t("Project settings could not be loaded", "无法加载 Project 设置")}</h2><Button variant="outline" class="mt-5 rounded-[9px] shadow-none" onclick={() => void load()}><RefreshCw class="size-4" />{t("Retry", "重试")}</Button></div>
  {:else}<div class="space-y-5"><form class="rounded-[16px] border border-divider bg-surface p-5 sm:p-6" onsubmit={save}><h2 class="font-semibold">{t("General", "常规")}</h2><p class="mt-1 text-sm text-muted-foreground">{t("Project identity is shared by every Environment and Resource.", "Project 身份由全部 Environment 与 Resource 共享。")}</p><label class="mt-6 block text-sm font-medium">{t("Name", "名称")}<input bind:value={name} required class="mt-2 h-10 w-full rounded-[9px] border border-input bg-background px-3 outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label><label class="mt-4 block text-sm font-medium">{t("Description", "描述")}<textarea bind:value={description} rows="4" class="mt-2 w-full resize-y rounded-[9px] border border-input bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"></textarea></label><div class="mt-6 flex items-center justify-between gap-3"><code class="text-xs text-muted-foreground">{project.slug}</code><Button type="submit" disabled={saving || !name.trim()} class="rounded-[9px]"><Save class="size-4" />{saving ? t("Saving…", "保存中…") : t("Save changes", "保存变更")}</Button></div></form>
  <section class="rounded-[16px] border border-divider bg-surface p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><h2 class="font-semibold">{t("Environments", "Environments")}</h2><p class="mt-1 text-sm text-muted-foreground">{t("Manage the lifecycle scopes owned by this Project.", "管理该 Project 拥有的生命周期范围。")}</p></div><Button variant="outline" class="rounded-[9px] shadow-none" onclick={() => (environmentFormOpen = !environmentFormOpen)}><Plus class="size-4" />{t("Add", "添加")}</Button></div>{#if environmentFormOpen}<form data-create-environment-form class="mt-5 grid gap-3 rounded-[12px] bg-muted/50 p-4 sm:grid-cols-[minmax(0,1fr)_160px_auto]" onsubmit={createEnvironment}><input bind:value={environmentName} required class="h-10 rounded-[9px] border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder={t("Environment name", "Environment 名称")} /><select bind:value={environmentKind} class="h-10 rounded-[9px] border border-input bg-background px-3 text-sm"><option value="development">Development</option><option value="test">Test</option><option value="staging">Staging</option><option value="production">Production</option><option value="custom">Custom</option></select><Button type="submit" class="rounded-[9px]" disabled={creatingEnvironment || !environmentName.trim()}>{creatingEnvironment ? t("Creating…", "创建中…") : t("Create", "创建")}</Button></form>{/if}<div class="mt-5 divide-y divide-divider">{#each environments?.items ?? [] as environment}<div class="flex items-center justify-between gap-3 py-3"><div class="flex items-center gap-3"><span class="grid size-9 place-items-center rounded-[10px] bg-primary/10 text-primary"><GitBranch class="size-4" /></span><div><p class="text-sm font-medium">{environment.name}</p><p class="mt-0.5 text-xs text-muted-foreground">{environment.kind}</p></div></div><span class="rounded-full bg-muted px-2.5 py-1 text-xs capitalize text-muted-foreground">{environment.lifecycleStatus}</span></div>{/each}</div></section></div>
  <aside class="rounded-[16px] border border-destructive/20 bg-destructive/[0.025] p-5"><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-[11px] bg-destructive/10 text-destructive"><ShieldAlert class="size-[18px]" /></span><div><h2 class="text-sm font-semibold">{t("Lifecycle", "生命周期")}</h2><p class="mt-0.5 text-xs capitalize text-muted-foreground">{project.lifecycleStatus}</p></div></div><p class="mt-5 text-sm leading-relaxed text-muted-foreground">{project.lifecycleStatus === "active" ? t("Archiving removes this Project from active work while keeping its history.", "归档会让该 Project 退出活跃工作，同时保留历史。") : t("Restore this Project to make it active again.", "恢复该 Project 以重新启用。")}</p><Button data-project-lifecycle-action variant="outline" class="mt-5 w-full rounded-[9px] shadow-none" disabled={actioning} onclick={() => void toggleLifecycle()}><Archive class="size-4" />{project.lifecycleStatus === "active" ? t("Archive Project", "归档 Project") : t("Restore Project", "恢复 Project")}</Button><div class="mt-5 border-t border-divider pt-4"><p class="text-xs font-medium">{t("Delete readiness", "删除就绪情况")}</p><p class="mt-2 text-xs leading-relaxed text-muted-foreground">{check?.eligible ? t("No blockers. Permanent deletion is available through the accepted operation.", "没有阻塞项，可通过正式操作永久删除。") : t(`${check?.blockers.length ?? 0} blocker groups must be resolved before deletion.`, `删除前需处理 ${check?.blockers.length ?? 0} 组阻塞项。`)}</p></div></aside>
  {#if message}<p class="col-span-full text-sm text-emerald-600">{message}</p>{/if}{#if actionError}<p class="col-span-full text-sm text-destructive">{actionError}</p>{/if}
  {/if}
</section>
