import { type PublicDocsHelpTopicId, resolvePublicDocsHelpHref } from "@appaloft/docs-registry";

function withDocs(summary: string, topicId: PublicDocsHelpTopicId): string {
  return `${summary}. Docs: ${resolvePublicDocsHelpHref(topicId)}`;
}

export const cliDocsHrefs = {
  deploymentSource: resolvePublicDocsHelpHref("deployment.source"),
  deploymentPreviewCleanup: resolvePublicDocsHelpHref("deployment.preview-cleanup"),
  deploymentSourceRelink: resolvePublicDocsHelpHref("deployment.source-relink"),
  projectLifecycle: resolvePublicDocsHelpHref("project.lifecycle"),
  serverDeploymentTarget: resolvePublicDocsHelpHref("server.deployment-target"),
  serverSshCredential: resolvePublicDocsHelpHref("server.ssh-credential"),
  serverConnectivityTest: resolvePublicDocsHelpHref("server.connectivity-test"),
  serverProxyReadiness: resolvePublicDocsHelpHref("server.proxy-readiness"),
  serverTerminalSession: resolvePublicDocsHelpHref("server.terminal-session"),
  resourceConcept: resolvePublicDocsHelpHref("resource.concept"),
  resourceSourceProfile: resolvePublicDocsHelpHref("resource.source-profile"),
  resourceRuntimeProfile: resolvePublicDocsHelpHref("resource.runtime-profile"),
  resourceHealthProfile: resolvePublicDocsHelpHref("resource.health-profile"),
  resourceNetworkProfile: resolvePublicDocsHelpHref("resource.network-profile"),
  environmentConcept: resolvePublicDocsHelpHref("environment.concept"),
  environmentVariablePrecedence: resolvePublicDocsHelpHref("environment.variable-precedence"),
  environmentDiffPromote: resolvePublicDocsHelpHref("environment.diff-promote"),
  domainGeneratedAccessRoute: resolvePublicDocsHelpHref("domain.generated-access-route"),
  domainCustomBinding: resolvePublicDocsHelpHref("domain.custom-domain-binding"),
  domainOwnershipCheck: resolvePublicDocsHelpHref("domain.ownership-check"),
  certificateReadiness: resolvePublicDocsHelpHref("certificate.readiness"),
  observabilityRuntimeLogs: resolvePublicDocsHelpHref("observability.runtime-logs"),
  observabilityHealthSummary: resolvePublicDocsHelpHref("observability.health-summary"),
  diagnosticsSafeSupportPayload: resolvePublicDocsHelpHref("diagnostics.safe-support-payload"),
} as const;

export const cliCommandDescriptions = {
  deploy: withDocs("Create a deployment", "deployment.source"),
  deploymentLogs: withDocs("Show deployment logs", "observability.runtime-logs"),
  deploymentList: withDocs("List deployments", "deployment.lifecycle"),
  deploymentShow: withDocs("Show deployment detail", "deployment.lifecycle"),
  deploymentEvents: withDocs(
    "Replay or follow deployment lifecycle events",
    "deployment.lifecycle",
  ),
  deployments: withDocs("Deployment queries", "deployment.lifecycle"),
  preview: withDocs("Preview deployment commands", "deployment.preview-cleanup"),
  previewCleanup: withDocs("Clean up a preview deployment context", "deployment.preview-cleanup"),
  sourceLinks: withDocs("Source fingerprint link operations", "deployment.source-relink"),
  sourceLinkRelink: withDocs(
    "Relink a source fingerprint to an explicit resource",
    "deployment.source-relink",
  ),
  project: withDocs("Project operations", "project.lifecycle"),
  projectCreate: withDocs("Create a project", "project.concept"),
  projectList: withDocs("List projects", "project.concept"),
  projectShow: withDocs("Show project identity and lifecycle", "project.lifecycle"),
  projectRename: withDocs("Rename a project", "project.lifecycle"),
  projectArchive: withDocs("Archive a project", "project.lifecycle"),
  server: withDocs("Server operations", "server.deployment-target"),
  serverRegister: withDocs("Register a server", "server.deployment-target"),
  serverList: withDocs("List servers", "server.deployment-target"),
  serverCredential: withDocs("Configure server SSH credential", "server.ssh-credential"),
  serverCredentialCreate: withDocs(
    "Create a reusable SSH credential from a private key file",
    "server.ssh-credential",
  ),
  serverCredentialList: withDocs("List reusable SSH credentials", "server.ssh-credential"),
  serverTest: withDocs("Test server connectivity", "server.connectivity-test"),
  serverDoctor: withDocs("Diagnose server SSH and Docker readiness", "server.connectivity-test"),
  serverProxy: withDocs("Server edge proxy operations", "server.proxy-readiness"),
  serverProxyRepair: withDocs(
    "Repair provider-owned edge proxy infrastructure",
    "server.proxy-readiness",
  ),
  serverTerminal: withDocs("Open a server terminal session", "server.terminal-session"),
  resource: withDocs("Resource operations", "resource.concept"),
  resourceCreate: withDocs("Create a resource", "resource.concept"),
  resourceList: withDocs("List resources", "resource.concept"),
  resourceShow: withDocs("Show resource profile", "resource.concept"),
  resourceArchive: withDocs("Archive a resource", "resource.concept"),
  resourceDelete: withDocs("Delete an archived resource", "resource.concept"),
  resourceTerminal: withDocs("Open a resource terminal session", "server.terminal-session"),
  resourceLogs: withDocs("Show resource runtime logs", "observability.runtime-logs"),
  resourceHealth: withDocs("Show current resource health", "observability.health-summary"),
  resourceConfigureSource: withDocs("Configure resource source profile", "resource.source-profile"),
  resourceConfigureRuntime: withDocs(
    "Configure resource runtime profile",
    "resource.runtime-profile",
  ),
  resourceConfigureHealth: withDocs("Configure resource health policy", "resource.health-profile"),
  resourceConfigureNetwork: withDocs(
    "Configure resource network profile",
    "resource.network-profile",
  ),
  resourceProxyConfig: withDocs("Show resource proxy configuration", "resource.network-profile"),
  resourceDiagnose: withDocs(
    "Copy resource diagnostic summary context",
    "diagnostics.safe-support-payload",
  ),
  environment: withDocs("Environment operations", "environment.concept"),
  environmentCreate: withDocs("Create an environment", "environment.concept"),
  environmentList: withDocs("List environments", "environment.concept"),
  environmentShow: withDocs("Show an environment", "environment.concept"),
  environmentSet: withDocs("Set an environment variable", "environment.variable-precedence"),
  environmentUnset: withDocs("Unset an environment variable", "environment.variable-precedence"),
  environmentDiff: withDocs("Diff two environments", "environment.diff-promote"),
  environmentPromote: withDocs("Promote an environment", "environment.diff-promote"),
  defaultAccess: withDocs(
    "Configure generated default access domain policy",
    "domain.generated-access-route",
  ),
  defaultAccessConfigure: withDocs(
    "Configure default access domain policy",
    "domain.generated-access-route",
  ),
  domainBinding: withDocs("Domain binding operations", "domain.custom-domain-binding"),
  domainBindingCreate: withDocs("Create a durable domain binding", "domain.custom-domain-binding"),
  domainBindingConfirmOwnership: withDocs(
    "Confirm domain binding ownership",
    "domain.ownership-check",
  ),
  domainBindingList: withDocs("List domain bindings", "domain.custom-domain-binding"),
  certificate: withDocs("Certificate operations", "certificate.readiness"),
  certificateIssueOrRenew: withDocs(
    "Request certificate issuance or renewal",
    "certificate.readiness",
  ),
  certificateImport: withDocs(
    "Import a manual certificate for a bound domain",
    "certificate.readiness",
  ),
  certificateList: withDocs("List certificate lifecycle state", "certificate.readiness"),
} as const;
