import { type PublicDocsHelpTopicId, resolvePublicDocsHelpHref } from "@appaloft/docs-registry";

function withDocs(summary: string, topicId: PublicDocsHelpTopicId): string {
  return `${summary}. Docs: ${resolvePublicDocsHelpHref(topicId)}`;
}

export const cliDocsHrefs = {
  deploymentSource: resolvePublicDocsHelpHref("deployment.source"),
  deploymentPlanPreview: resolvePublicDocsHelpHref("deployment.plan-preview"),
  deploymentPreviewCleanup: resolvePublicDocsHelpHref("deployment.preview-cleanup"),
  deploymentSourceRelink: resolvePublicDocsHelpHref("deployment.source-relink"),
  deploymentRecoveryReadiness: resolvePublicDocsHelpHref("deployment.recovery-readiness"),
  projectLifecycle: resolvePublicDocsHelpHref("project.lifecycle"),
  serverDeploymentTarget: resolvePublicDocsHelpHref("server.deployment-target"),
  serverSshCredential: resolvePublicDocsHelpHref("server.ssh-credential"),
  serverConnectivityTest: resolvePublicDocsHelpHref("server.connectivity-test"),
  serverProxyReadiness: resolvePublicDocsHelpHref("server.proxy-readiness"),
  serverTerminalSession: resolvePublicDocsHelpHref("server.terminal-session"),
  resourceConcept: resolvePublicDocsHelpHref("resource.concept"),
  resourceSourceProfile: resolvePublicDocsHelpHref("resource.source-profile"),
  resourceRuntimeProfile: resolvePublicDocsHelpHref("resource.runtime-profile"),
  resourceHealthProfile: resolvePublicDocsHelpHref("resource.health-profile"),
  resourceNetworkProfile: resolvePublicDocsHelpHref("resource.network-profile"),
  resourceAccessProfile: resolvePublicDocsHelpHref("resource.access-profile"),
  storageVolumeLifecycle: resolvePublicDocsHelpHref("storage.volume-lifecycle"),
  environmentConcept: resolvePublicDocsHelpHref("environment.concept"),
  environmentLifecycle: resolvePublicDocsHelpHref("environment.lifecycle"),
  environmentVariablePrecedence: resolvePublicDocsHelpHref("environment.variable-precedence"),
  environmentDiffPromote: resolvePublicDocsHelpHref("environment.diff-promote"),
  domainGeneratedAccessRoute: resolvePublicDocsHelpHref("domain.generated-access-route"),
  domainCustomBinding: resolvePublicDocsHelpHref("domain.custom-domain-binding"),
  domainOwnershipCheck: resolvePublicDocsHelpHref("domain.ownership-check"),
  certificateReadiness: resolvePublicDocsHelpHref("certificate.readiness"),
  observabilityRuntimeLogs: resolvePublicDocsHelpHref("observability.runtime-logs"),
  observabilityHealthSummary: resolvePublicDocsHelpHref("observability.health-summary"),
  diagnosticsSafeSupportPayload: resolvePublicDocsHelpHref("diagnostics.safe-support-payload"),
  diagnosticsAccessFailureRequestId: resolvePublicDocsHelpHref(
    "diagnostics.access-failure-request-id",
  ),
  diagnosticsRuntimeTargetCapacity: resolvePublicDocsHelpHref(
    "diagnostics.runtime-target-capacity",
  ),
  operatorWorkLedger: resolvePublicDocsHelpHref("operator.work-ledger"),
  remoteStateLock: resolvePublicDocsHelpHref("errors.remote-state-lock"),
} as const;

export const cliCommandDescriptions = {
  deploy: withDocs("Create a deployment", "deployment.source"),
  deploymentPlan: withDocs("Preview deployment plan without execution", "deployment.plan-preview"),
  deploymentLogs: withDocs("Show deployment logs", "observability.runtime-logs"),
  deploymentList: withDocs("List deployments", "deployment.lifecycle"),
  deploymentShow: withDocs("Show deployment detail", "deployment.lifecycle"),
  deploymentRecoveryReadiness: withDocs(
    "Show retry, redeploy, and rollback readiness for a deployment",
    "deployment.recovery-readiness",
  ),
  deploymentRetry: withDocs(
    "Retry a failed or canceled deployment attempt",
    "deployment.recovery-readiness",
  ),
  deploymentRedeploy: withDocs(
    "Redeploy the current resource profile",
    "deployment.recovery-readiness",
  ),
  deploymentEvents: withDocs(
    "Replay or follow deployment lifecycle events",
    "deployment.lifecycle",
  ),
  deployments: withDocs("Deployment queries", "deployment.lifecycle"),
  preview: withDocs("Preview deployment commands", "deployment.preview-cleanup"),
  previewCleanup: withDocs("Clean up a preview deployment context", "deployment.preview-cleanup"),
  sourceLinks: withDocs("Source fingerprint link operations", "deployment.source-relink"),
  sourceLinkRelink: withDocs(
    "Relink a source fingerprint to an explicit resource",
    "deployment.source-relink",
  ),
  remoteState: withDocs("Remote state diagnostics", "errors.remote-state-lock"),
  remoteStateLock: withDocs("SSH remote-state lock diagnostics", "errors.remote-state-lock"),
  remoteStateLockInspect: withDocs(
    "Inspect the SSH remote-state mutation lock",
    "errors.remote-state-lock",
  ),
  remoteStateLockRecoverStale: withDocs(
    "Archive a stale SSH remote-state mutation lock",
    "errors.remote-state-lock",
  ),
  operatorWork: withDocs("Background work visibility", "operator.work-ledger"),
  operatorWorkList: withDocs(
    "List background work and latest failure state without recovery mutation",
    "operator.work-ledger",
  ),
  operatorWorkShow: withDocs(
    "Show one background work item without retrying or cleaning it up",
    "operator.work-ledger",
  ),
  project: withDocs("Project operations", "project.lifecycle"),
  projectCreate: withDocs("Create a project", "project.concept"),
  projectList: withDocs("List projects", "project.concept"),
  projectShow: withDocs("Show project identity and lifecycle", "project.lifecycle"),
  projectRename: withDocs("Rename a project", "project.lifecycle"),
  projectArchive: withDocs("Archive a project", "project.lifecycle"),
  server: withDocs("Server operations", "server.deployment-target"),
  serverRegister: withDocs("Register a server", "server.deployment-target"),
  serverList: withDocs("List servers", "server.deployment-target"),
  serverShow: withDocs("Show server detail", "server.deployment-target"),
  serverRename: withDocs("Rename a server deployment target", "server.deployment-target"),
  serverDeactivate: withDocs("Deactivate a server deployment target", "server.deployment-target"),
  serverDeleteCheck: withDocs(
    "Check whether a server can be safely deleted",
    "server.deployment-target",
  ),
  serverDelete: withDocs(
    "Delete a deactivated server after delete-safety blockers are clear",
    "server.deployment-target",
  ),
  serverCredential: withDocs("Configure server SSH credential", "server.ssh-credential"),
  serverCredentialCreate: withDocs(
    "Create a reusable SSH credential from a private key file",
    "server.ssh-credential",
  ),
  serverCredentialList: withDocs("List reusable SSH credentials", "server.ssh-credential"),
  serverCredentialShow: withDocs(
    "Show reusable SSH credential detail and usage",
    "server.ssh-credential",
  ),
  serverCredentialDelete: withDocs(
    "Delete an unused reusable SSH credential after typed confirmation",
    "server.ssh-credential",
  ),
  serverCredentialRotate: withDocs(
    "Rotate a reusable SSH credential after typed confirmation and usage acknowledgement",
    "server.ssh-credential",
  ),
  serverTest: withDocs("Test server connectivity", "server.connectivity-test"),
  serverDoctor: withDocs("Diagnose server SSH and Docker readiness", "server.connectivity-test"),
  serverCapacity: withDocs("Server capacity diagnostics", "diagnostics.runtime-target-capacity"),
  serverCapacityInspect: withDocs(
    "Inspect disk, inode, Docker, and Appaloft runtime capacity without cleanup",
    "diagnostics.runtime-target-capacity",
  ),
  serverProxy: withDocs("Server edge proxy operations", "server.proxy-readiness"),
  serverProxyRepair: withDocs(
    "Repair provider-owned edge proxy infrastructure",
    "server.proxy-readiness",
  ),
  serverProxyConfigure: withDocs(
    "Configure desired edge proxy kind for future routes",
    "server.proxy-readiness",
  ),
  serverTerminal: withDocs("Open a server terminal session", "server.terminal-session"),
  resource: withDocs("Resource operations", "resource.concept"),
  resourceCreate: withDocs("Create a resource", "resource.concept"),
  resourceList: withDocs("List resources", "resource.concept"),
  resourceShow: withDocs("Show resource profile", "resource.concept"),
  resourceArchive: withDocs("Archive a resource", "resource.concept"),
  resourceDelete: withDocs("Delete an archived resource", "resource.concept"),
  resourceTerminal: withDocs("Open a resource terminal session", "server.terminal-session"),
  resourceLogs: withDocs("Show resource runtime logs", "observability.runtime-logs"),
  resourceHealth: withDocs("Show current resource health", "observability.health-summary"),
  resourceConfigureSource: withDocs("Configure resource source profile", "resource.source-profile"),
  resourceConfigureRuntime: withDocs(
    "Configure resource runtime profile",
    "resource.runtime-profile",
  ),
  resourceConfigureHealth: withDocs("Configure resource health policy", "resource.health-profile"),
  resourceConfigureNetwork: withDocs(
    "Configure resource network profile",
    "resource.network-profile",
  ),
  resourceConfigureAccess: withDocs(
    "Configure resource generated access profile",
    "resource.access-profile",
  ),
  resourceStorage: withDocs("Resource storage attachment operations", "storage.volume-lifecycle"),
  resourceAttachStorage: withDocs(
    "Attach storage to a resource at a destination path",
    "storage.volume-lifecycle",
  ),
  resourceDetachStorage: withDocs(
    "Detach storage from a resource without deleting the volume",
    "storage.volume-lifecycle",
  ),
  resourceDependency: withDocs("Resource dependency binding operations", "resource.concept"),
  resourceDependencyBind: withDocs("Bind a dependency resource to a resource", "resource.concept"),
  resourceDependencyUnbind: withDocs(
    "Unbind a dependency resource without deleting it",
    "resource.concept",
  ),
  resourceDependencyRotateSecret: withDocs(
    "Rotate a resource dependency binding secret reference",
    "resource.concept",
  ),
  resourceDependencyList: withDocs("List resource dependency bindings", "resource.concept"),
  resourceDependencyShow: withDocs("Show one resource dependency binding", "resource.concept"),
  storage: withDocs("Storage operations", "storage.volume-lifecycle"),
  storageVolume: withDocs("Storage volume operations", "storage.volume-lifecycle"),
  storageVolumeCreate: withDocs(
    "Create a named volume or bind mount metadata record",
    "storage.volume-lifecycle",
  ),
  storageVolumeList: withDocs("List storage volumes", "storage.volume-lifecycle"),
  storageVolumeShow: withDocs("Show storage volume detail", "storage.volume-lifecycle"),
  storageVolumeRename: withDocs("Rename a storage volume", "storage.volume-lifecycle"),
  storageVolumeDelete: withDocs("Delete an unattached storage volume", "storage.volume-lifecycle"),
  dependency: withDocs("Dependency resource operations", "resource.concept"),
  dependencyPostgres: withDocs("Postgres dependency resource operations", "resource.concept"),
  dependencyPostgresProvision: withDocs(
    "Create an Appaloft-managed Postgres dependency resource record",
    "resource.concept",
  ),
  dependencyPostgresImport: withDocs(
    "Import an external Postgres dependency resource",
    "resource.concept",
  ),
  dependencyRedis: withDocs("Redis dependency resource operations", "resource.concept"),
  dependencyRedisProvision: withDocs(
    "Create an Appaloft-managed Redis dependency resource record",
    "resource.concept",
  ),
  dependencyRedisImport: withDocs(
    "Import an external Redis dependency resource",
    "resource.concept",
  ),
  dependencyList: withDocs("List dependency resources", "resource.concept"),
  dependencyShow: withDocs("Show dependency resource detail", "resource.concept"),
  dependencyRename: withDocs("Rename a dependency resource", "resource.concept"),
  dependencyDelete: withDocs(
    "Delete a dependency resource after safety checks",
    "resource.concept",
  ),
  dependencyBackup: withDocs("Dependency resource backup operations", "resource.concept"),
  dependencyBackupCreate: withDocs(
    "Create a backup restore point for a dependency resource",
    "resource.concept",
  ),
  dependencyBackupList: withDocs("List dependency resource backups", "resource.concept"),
  dependencyBackupShow: withDocs("Show dependency resource backup detail", "resource.concept"),
  dependencyBackupRestore: withDocs(
    "Restore a dependency resource backup in place",
    "resource.concept",
  ),
  resourceSetVariable: withDocs(
    "Set a resource-scoped variable override",
    "environment.variable-precedence",
  ),
  resourceImportVariables: withDocs(
    "Import pasted .env variables into one resource",
    "environment.variable-precedence",
  ),
  resourceUnsetVariable: withDocs(
    "Unset a resource-scoped variable override",
    "environment.variable-precedence",
  ),
  resourceEffectiveConfig: withDocs(
    "Show masked effective resource configuration",
    "environment.variable-precedence",
  ),
  resourceProxyConfig: withDocs("Show resource proxy configuration", "resource.network-profile"),
  resourceDiagnose: withDocs(
    "Copy resource diagnostic summary context",
    "diagnostics.safe-support-payload",
  ),
  resourceAccessFailure: withDocs(
    "Look up safe access failure evidence by request id",
    "diagnostics.access-failure-request-id",
  ),
  environment: withDocs("Environment operations", "environment.concept"),
  environmentCreate: withDocs("Create an environment", "environment.concept"),
  environmentList: withDocs("List environments", "environment.concept"),
  environmentShow: withDocs("Show an environment", "environment.concept"),
  environmentRename: withDocs("Rename an environment", "environment.lifecycle"),
  environmentArchive: withDocs("Archive an environment", "environment.lifecycle"),
  environmentClone: withDocs("Clone an environment", "environment.lifecycle"),
  environmentLock: withDocs("Lock an environment", "environment.lifecycle"),
  environmentUnlock: withDocs("Unlock an environment", "environment.lifecycle"),
  environmentSet: withDocs("Set an environment variable", "environment.variable-precedence"),
  environmentUnset: withDocs("Unset an environment variable", "environment.variable-precedence"),
  environmentEffectivePrecedence: withDocs(
    "Show masked effective environment precedence",
    "environment.variable-precedence",
  ),
  environmentDiff: withDocs("Diff two environments", "environment.diff-promote"),
  environmentPromote: withDocs("Promote an environment", "environment.diff-promote"),
  defaultAccess: withDocs(
    "Configure generated default access domain policy",
    "domain.generated-access-route",
  ),
  defaultAccessConfigure: withDocs(
    "Configure default access domain policy",
    "domain.generated-access-route",
  ),
  defaultAccessList: withDocs(
    "List default access domain policies",
    "domain.generated-access-route",
  ),
  defaultAccessShow: withDocs("Show default access domain policy", "domain.generated-access-route"),
  domainBinding: withDocs("Domain binding operations", "domain.custom-domain-binding"),
  domainBindingCreate: withDocs("Create a durable domain binding", "domain.custom-domain-binding"),
  domainBindingShow: withDocs("Show domain binding readiness", "domain.custom-domain-binding"),
  domainBindingConfigureRoute: withDocs(
    "Configure domain binding route behavior",
    "domain.custom-domain-binding",
  ),
  domainBindingConfirmOwnership: withDocs(
    "Confirm domain binding ownership",
    "domain.ownership-check",
  ),
  domainBindingDeleteCheck: withDocs(
    "Check whether a domain binding can be deleted safely",
    "domain.custom-domain-binding",
  ),
  domainBindingDelete: withDocs("Delete a domain binding safely", "domain.custom-domain-binding"),
  domainBindingRetryVerification: withDocs(
    "Retry domain binding ownership verification",
    "domain.ownership-check",
  ),
  domainBindingList: withDocs("List domain bindings", "domain.custom-domain-binding"),
  certificate: withDocs("Certificate operations", "certificate.readiness"),
  certificateIssueOrRenew: withDocs(
    "Request certificate issuance or renewal",
    "certificate.readiness",
  ),
  certificateImport: withDocs(
    "Import a manual certificate for a bound domain",
    "certificate.readiness",
  ),
  certificateList: withDocs("List certificate lifecycle state", "certificate.readiness"),
  certificateShow: withDocs("Show certificate lifecycle state", "certificate.readiness"),
  certificateRetry: withDocs("Retry provider certificate issuance", "certificate.readiness"),
  certificateRevoke: withDocs("Revoke an active certificate", "certificate.readiness"),
  certificateDelete: withDocs("Delete certificate active lifecycle state", "certificate.readiness"),
} as const;
