export const tokens = {
  clock: Symbol.for("appaloft.clock"),
  idGenerator: Symbol.for("appaloft.id_generator"),
  logger: Symbol.for("appaloft.logger"),
  eventBus: Symbol.for("appaloft.event_bus"),
  mutationCoordinator: Symbol.for("appaloft.mutation_coordinator"),
  deploymentProgressReporter: Symbol.for("appaloft.deployment_progress_reporter"),
  deploymentEventObserver: Symbol.for("appaloft.deployment_event_observer"),
  sourceLinkRepository: Symbol.for("appaloft.source_link_repository"),
  defaultAccessDomainPolicyRepository: Symbol.for(
    "appaloft.default_access_domain_policy_repository",
  ),
  defaultAccessDomainPolicySupport: Symbol.for("appaloft.default_access_domain_policy_support"),
  serverConnectivityChecker: Symbol.for("appaloft.server_connectivity_checker"),
  runtimeTargetCapacityInspector: Symbol.for("appaloft.runtime_target_capacity_inspector"),
  serverEdgeProxyBootstrapper: Symbol.for("appaloft.server_edge_proxy_bootstrapper"),
  deploymentConfigReader: Symbol.for("appaloft.deployment_config_reader"),
  projectRepository: Symbol.for("appaloft.project_repository"),
  serverRepository: Symbol.for("appaloft.server_repository"),
  serverDeletionBlockerReader: Symbol.for("appaloft.server_deletion_blocker_reader"),
  destinationRepository: Symbol.for("appaloft.destination_repository"),
  environmentRepository: Symbol.for("appaloft.environment_repository"),
  resourceRepository: Symbol.for("appaloft.resource_repository"),
  scheduledTaskDefinitionRepository: Symbol.for("appaloft.scheduled_task_definition_repository"),
  scheduledTaskRunAttemptRepository: Symbol.for("appaloft.scheduled_task_run_attempt_repository"),
  scheduledTaskRunLogRecorder: Symbol.for("appaloft.scheduled_task_run_log_recorder"),
  scheduledTaskDueCandidateReader: Symbol.for("appaloft.scheduled_task_due_candidate_reader"),
  dependencyResourceRepository: Symbol.for("appaloft.dependency_resource_repository"),
  dependencyResourceBackupRepository: Symbol.for("appaloft.dependency_resource_backup_repository"),
  previewEnvironmentRepository: Symbol.for("appaloft.preview_environment_repository"),
  previewPolicyRepository: Symbol.for("appaloft.preview_policy_repository"),
  previewPolicyDecisionRecorder: Symbol.for("appaloft.preview_policy_decision_recorder"),
  previewFeedbackWriter: Symbol.for("appaloft.preview_feedback_writer"),
  previewFeedbackRecorder: Symbol.for("appaloft.preview_feedback_recorder"),
  previewEnvironmentCleaner: Symbol.for("appaloft.preview_environment_cleaner"),
  previewCleanupAttemptRecorder: Symbol.for("appaloft.preview_cleanup_attempt_recorder"),
  previewCleanupRetryCandidateReader: Symbol.for("appaloft.preview_cleanup_retry_candidate_reader"),
  resourceDependencyBindingRepository: Symbol.for(
    "appaloft.resource_dependency_binding_repository",
  ),
  dependencyResourceDeleteSafetyReader: Symbol.for(
    "appaloft.dependency_resource_delete_safety_reader",
  ),
  storageVolumeRepository: Symbol.for("appaloft.storage_volume_repository"),
  resourceDeletionBlockerReader: Symbol.for("appaloft.resource_deletion_blocker_reader"),
  deploymentRepository: Symbol.for("appaloft.deployment_repository"),
  domainBindingRepository: Symbol.for("appaloft.domain_binding_repository"),
  domainOwnershipVerifier: Symbol.for("appaloft.domain_ownership_verifier"),
  domainRouteFailureCandidateReader: Symbol.for("appaloft.domain_route_failure_candidate_reader"),
  domainRouteBindingReader: Symbol.for("appaloft.domain_route_binding_reader"),
  serverAppliedRouteStateRepository: Symbol.for("appaloft.server_applied_route_state_repository"),
  certificateRepository: Symbol.for("appaloft.certificate_repository"),
  certificateRetryCandidateReader: Symbol.for("appaloft.certificate_retry_candidate_reader"),
  sshCredentialRepository: Symbol.for("appaloft.ssh_credential_repository"),
  certificateProviderSelectionPolicy: Symbol.for("appaloft.certificate_provider_selection_policy"),
  certificateProvider: Symbol.for("appaloft.certificate_provider"),
  certificateMaterialValidator: Symbol.for("appaloft.certificate_material_validator"),
  certificateSecretStore: Symbol.for("appaloft.certificate_secret_store"),
  dependencyBindingSecretStore: Symbol.for("appaloft.dependency_binding_secret_store"),
  certificateHttpChallengeTokenStore: Symbol.for("appaloft.certificate_http_challenge_token_store"),
  deploymentContextDefaultsPolicy: Symbol.for("appaloft.deployment_context_defaults_policy"),
  projectReadModel: Symbol.for("appaloft.project_read_model"),
  serverReadModel: Symbol.for("appaloft.server_read_model"),
  environmentReadModel: Symbol.for("appaloft.environment_read_model"),
  resourceReadModel: Symbol.for("appaloft.resource_read_model"),
  scheduledTaskReadModel: Symbol.for("appaloft.scheduled_task_read_model"),
  scheduledTaskRunReadModel: Symbol.for("appaloft.scheduled_task_run_read_model"),
  scheduledTaskRunLogReadModel: Symbol.for("appaloft.scheduled_task_run_log_read_model"),
  dependencyResourceReadModel: Symbol.for("appaloft.dependency_resource_read_model"),
  dependencyResourceBackupReadModel: Symbol.for("appaloft.dependency_resource_backup_read_model"),
  resourceDependencyBindingReadModel: Symbol.for("appaloft.resource_dependency_binding_read_model"),
  storageVolumeReadModel: Symbol.for("appaloft.storage_volume_read_model"),
  resourceAccessFailureEvidenceRecorder: Symbol.for(
    "appaloft.resource_access_failure_evidence_recorder",
  ),
  resourceAccessFailureEvidenceReadModel: Symbol.for(
    "appaloft.resource_access_failure_evidence_read_model",
  ),
  sourceEventRecorder: Symbol.for("appaloft.source_event_recorder"),
  sourceEventPolicyReader: Symbol.for("appaloft.source_event_policy_reader"),
  sourceEventDeploymentDispatcher: Symbol.for("appaloft.source_event_deployment_dispatcher"),
  sourceEventReadModel: Symbol.for("appaloft.source_event_read_model"),
  previewLifecycleService: Symbol.for("appaloft.preview_lifecycle_service"),
  previewFeedbackService: Symbol.for("appaloft.preview_feedback_service"),
  previewDeploymentProcessManager: Symbol.for("appaloft.preview_deployment_process_manager"),
  previewPullRequestEventIngestService: Symbol.for(
    "appaloft.preview_pull_request_event_ingest_service",
  ),
  previewEnvironmentReadModel: Symbol.for("appaloft.preview_environment_read_model"),
  previewPolicyReadModel: Symbol.for("appaloft.preview_policy_read_model"),
  previewPolicyDecisionReadModel: Symbol.for("appaloft.preview_policy_decision_read_model"),
  deploymentReadModel: Symbol.for("appaloft.deployment_read_model"),
  domainBindingReadModel: Symbol.for("appaloft.domain_binding_read_model"),
  certificateReadModel: Symbol.for("appaloft.certificate_read_model"),
  processAttemptRecorder: Symbol.for("appaloft.process_attempt_recorder"),
  processAttemptReadModel: Symbol.for("appaloft.process_attempt_read_model"),
  sshCredentialReadModel: Symbol.for("appaloft.ssh_credential_read_model"),
  sshCredentialUsageReader: Symbol.for("appaloft.ssh_credential_usage_reader"),
  archiveProjectUseCase: Symbol.for("appaloft.archive_project_use_case"),
  createProjectUseCase: Symbol.for("appaloft.create_project_use_case"),
  listProjectsQueryService: Symbol.for("appaloft.list_projects_query_service"),
  renameProjectUseCase: Symbol.for("appaloft.rename_project_use_case"),
  showProjectQueryService: Symbol.for("appaloft.show_project_query_service"),
  configureDefaultAccessDomainPolicyUseCase: Symbol.for(
    "appaloft.configure_default_access_domain_policy_use_case",
  ),
  listDefaultAccessDomainPoliciesQueryService: Symbol.for(
    "appaloft.list_default_access_domain_policies_query_service",
  ),
  showDefaultAccessDomainPolicyQueryService: Symbol.for(
    "appaloft.show_default_access_domain_policy_query_service",
  ),
  registerServerUseCase: Symbol.for("appaloft.register_server_use_case"),
  configureServerCredentialUseCase: Symbol.for("appaloft.configure_server_credential_use_case"),
  createSshCredentialUseCase: Symbol.for("appaloft.create_ssh_credential_use_case"),
  listSshCredentialsQueryService: Symbol.for("appaloft.list_ssh_credentials_query_service"),
  showSshCredentialQueryService: Symbol.for("appaloft.show_ssh_credential_query_service"),
  listServersQueryService: Symbol.for("appaloft.list_servers_query_service"),
  showServerQueryService: Symbol.for("appaloft.show_server_query_service"),
  inspectServerCapacityQueryService: Symbol.for("appaloft.inspect_server_capacity_query_service"),
  renameServerUseCase: Symbol.for("appaloft.rename_server_use_case"),
  configureServerEdgeProxyUseCase: Symbol.for("appaloft.configure_server_edge_proxy_use_case"),
  deactivateServerUseCase: Symbol.for("appaloft.deactivate_server_use_case"),
  deleteServerUseCase: Symbol.for("appaloft.delete_server_use_case"),
  deleteSshCredentialUseCase: Symbol.for("appaloft.delete_ssh_credential_use_case"),
  rotateSshCredentialUseCase: Symbol.for("appaloft.rotate_ssh_credential_use_case"),
  checkServerDeleteSafetyQueryService: Symbol.for(
    "appaloft.check_server_delete_safety_query_service",
  ),
  testServerConnectivityUseCase: Symbol.for("appaloft.test_server_connectivity_use_case"),
  bootstrapServerProxyUseCase: Symbol.for("appaloft.bootstrap_server_proxy_use_case"),
  archiveEnvironmentUseCase: Symbol.for("appaloft.archive_environment_use_case"),
  cloneEnvironmentUseCase: Symbol.for("appaloft.clone_environment_use_case"),
  renameEnvironmentUseCase: Symbol.for("appaloft.rename_environment_use_case"),
  lockEnvironmentUseCase: Symbol.for("appaloft.lock_environment_use_case"),
  unlockEnvironmentUseCase: Symbol.for("appaloft.unlock_environment_use_case"),
  createEnvironmentUseCase: Symbol.for("appaloft.create_environment_use_case"),
  listEnvironmentsQueryService: Symbol.for("appaloft.list_environments_query_service"),
  showEnvironmentQueryService: Symbol.for("appaloft.show_environment_query_service"),
  environmentEffectivePrecedenceQueryService: Symbol.for(
    "appaloft.environment_effective_precedence_query_service",
  ),
  createResourceUseCase: Symbol.for("appaloft.create_resource_use_case"),
  archiveResourceUseCase: Symbol.for("appaloft.archive_resource_use_case"),
  deleteResourceUseCase: Symbol.for("appaloft.delete_resource_use_case"),
  configureResourceAutoDeployUseCase: Symbol.for(
    "appaloft.configure_resource_auto_deploy_use_case",
  ),
  configureResourceSourceUseCase: Symbol.for("appaloft.configure_resource_source_use_case"),
  configureResourceAccessUseCase: Symbol.for("appaloft.configure_resource_access_use_case"),
  configureResourceHealthUseCase: Symbol.for("appaloft.configure_resource_health_use_case"),
  configureResourceNetworkUseCase: Symbol.for("appaloft.configure_resource_network_use_case"),
  configureResourceRuntimeUseCase: Symbol.for("appaloft.configure_resource_runtime_use_case"),
  importResourceVariablesUseCase: Symbol.for("appaloft.import_resource_variables_use_case"),
  setResourceVariableUseCase: Symbol.for("appaloft.set_resource_variable_use_case"),
  unsetResourceVariableUseCase: Symbol.for("appaloft.unset_resource_variable_use_case"),
  attachResourceStorageUseCase: Symbol.for("appaloft.attach_resource_storage_use_case"),
  detachResourceStorageUseCase: Symbol.for("appaloft.detach_resource_storage_use_case"),
  bindResourceDependencyUseCase: Symbol.for("appaloft.bind_resource_dependency_use_case"),
  unbindResourceDependencyUseCase: Symbol.for("appaloft.unbind_resource_dependency_use_case"),
  rotateResourceDependencyBindingSecretUseCase: Symbol.for(
    "appaloft.rotate_resource_dependency_binding_secret_use_case",
  ),
  listResourcesQueryService: Symbol.for("appaloft.list_resources_query_service"),
  showResourceQueryService: Symbol.for("appaloft.show_resource_query_service"),
  listResourceDependencyBindingsQueryService: Symbol.for(
    "appaloft.list_resource_dependency_bindings_query_service",
  ),
  showResourceDependencyBindingQueryService: Symbol.for(
    "appaloft.show_resource_dependency_binding_query_service",
  ),
  provisionPostgresDependencyResourceUseCase: Symbol.for(
    "appaloft.provision_postgres_dependency_resource_use_case",
  ),
  importPostgresDependencyResourceUseCase: Symbol.for(
    "appaloft.import_postgres_dependency_resource_use_case",
  ),
  provisionRedisDependencyResourceUseCase: Symbol.for(
    "appaloft.provision_redis_dependency_resource_use_case",
  ),
  importRedisDependencyResourceUseCase: Symbol.for(
    "appaloft.import_redis_dependency_resource_use_case",
  ),
  renameDependencyResourceUseCase: Symbol.for("appaloft.rename_dependency_resource_use_case"),
  deleteDependencyResourceUseCase: Symbol.for("appaloft.delete_dependency_resource_use_case"),
  managedPostgresProvider: Symbol.for("appaloft.managed_postgres_provider"),
  dependencyResourceBackupProvider: Symbol.for("appaloft.dependency_resource_backup_provider"),
  createDependencyResourceBackupUseCase: Symbol.for(
    "appaloft.create_dependency_resource_backup_use_case",
  ),
  restoreDependencyResourceBackupUseCase: Symbol.for(
    "appaloft.restore_dependency_resource_backup_use_case",
  ),
  listDependencyResourcesQueryService: Symbol.for(
    "appaloft.list_dependency_resources_query_service",
  ),
  showDependencyResourceQueryService: Symbol.for("appaloft.show_dependency_resource_query_service"),
  listDependencyResourceBackupsQueryService: Symbol.for(
    "appaloft.list_dependency_resource_backups_query_service",
  ),
  showDependencyResourceBackupQueryService: Symbol.for(
    "appaloft.show_dependency_resource_backup_query_service",
  ),
  createStorageVolumeUseCase: Symbol.for("appaloft.create_storage_volume_use_case"),
  renameStorageVolumeUseCase: Symbol.for("appaloft.rename_storage_volume_use_case"),
  deleteStorageVolumeUseCase: Symbol.for("appaloft.delete_storage_volume_use_case"),
  listStorageVolumesQueryService: Symbol.for("appaloft.list_storage_volumes_query_service"),
  showStorageVolumeQueryService: Symbol.for("appaloft.show_storage_volume_query_service"),
  resourceEffectiveConfigQueryService: Symbol.for(
    "appaloft.resource_effective_config_query_service",
  ),
  resourceDiagnosticSummaryQueryService: Symbol.for(
    "appaloft.resource_diagnostic_summary_query_service",
  ),
  resourceAccessFailureEvidenceLookupQueryService: Symbol.for(
    "appaloft.resource_access_failure_evidence_lookup_query_service",
  ),
  automaticRouteContextLookupService: Symbol.for("appaloft.automatic_route_context_lookup_service"),
  resourceHealthQueryService: Symbol.for("appaloft.resource_health_query_service"),
  resourceHealthProbeRunner: Symbol.for("appaloft.resource_health_probe_runner"),
  resourceRuntimeLogsQueryService: Symbol.for("appaloft.resource_runtime_logs_query_service"),
  resourceRuntimeControlUseCase: Symbol.for("appaloft.resource_runtime_control_use_case"),
  resourceRuntimeControlTargetPort: Symbol.for("appaloft.resource_runtime_control_target_port"),
  resourceRuntimeControlAttemptRecorder: Symbol.for(
    "appaloft.resource_runtime_control_attempt_recorder",
  ),
  createScheduledTaskUseCase: Symbol.for("appaloft.create_scheduled_task_use_case"),
  configureScheduledTaskUseCase: Symbol.for("appaloft.configure_scheduled_task_use_case"),
  deleteScheduledTaskUseCase: Symbol.for("appaloft.delete_scheduled_task_use_case"),
  listScheduledTasksQueryService: Symbol.for("appaloft.list_scheduled_tasks_query_service"),
  showScheduledTaskQueryService: Symbol.for("appaloft.show_scheduled_task_query_service"),
  listScheduledTaskRunsQueryService: Symbol.for("appaloft.list_scheduled_task_runs_query_service"),
  showScheduledTaskRunQueryService: Symbol.for("appaloft.show_scheduled_task_run_query_service"),
  scheduledTaskRunLogsQueryService: Symbol.for("appaloft.scheduled_task_run_logs_query_service"),
  scheduledTaskRunAdmissionService: Symbol.for("appaloft.scheduled_task_run_admission_service"),
  scheduledTaskRunWorker: Symbol.for("appaloft.scheduled_task_run_worker"),
  scheduledTaskRuntimePort: Symbol.for("appaloft.scheduled_task_runtime_port"),
  runScheduledTaskNowUseCase: Symbol.for("appaloft.run_scheduled_task_now_use_case"),
  scheduledTaskScheduler: Symbol.for("appaloft.scheduled_task_scheduler"),
  ingestSourceEventUseCase: Symbol.for("appaloft.ingest_source_event_use_case"),
  sourceEventVerificationPort: Symbol.for("appaloft.source_event_verification_port"),
  githubSourceEventWebhookVerifier: Symbol.for("appaloft.github_source_event_webhook_verifier"),
  githubPreviewPullRequestWebhookVerifier: Symbol.for(
    "appaloft.github_preview_pull_request_webhook_verifier",
  ),
  listSourceEventsQueryService: Symbol.for("appaloft.list_source_events_query_service"),
  showSourceEventQueryService: Symbol.for("appaloft.show_source_event_query_service"),
  configurePreviewPolicyUseCase: Symbol.for("appaloft.configure_preview_policy_use_case"),
  showPreviewPolicyQueryService: Symbol.for("appaloft.show_preview_policy_query_service"),
  listPreviewEnvironmentsQueryService: Symbol.for(
    "appaloft.list_preview_environments_query_service",
  ),
  showPreviewEnvironmentQueryService: Symbol.for("appaloft.show_preview_environment_query_service"),
  previewEnvironmentCleanupService: Symbol.for("appaloft.preview_environment_cleanup_service"),
  previewCleanupRetryScheduler: Symbol.for("appaloft.preview_cleanup_retry_scheduler"),
  openTerminalSessionUseCase: Symbol.for("appaloft.open_terminal_session_use_case"),
  relinkSourceLinkUseCase: Symbol.for("appaloft.relink_source_link_use_case"),
  resourceProxyConfigurationPreviewQueryService: Symbol.for(
    "appaloft.resource_proxy_configuration_preview_query_service",
  ),
  setEnvironmentVariableUseCase: Symbol.for("appaloft.set_environment_variable_use_case"),
  unsetEnvironmentVariableUseCase: Symbol.for("appaloft.unset_environment_variable_use_case"),
  diffEnvironmentsQueryService: Symbol.for("appaloft.diff_environments_query_service"),
  promoteEnvironmentUseCase: Symbol.for("appaloft.promote_environment_use_case"),
  createDeploymentUseCase: Symbol.for("appaloft.create_deployment_use_case"),
  retryDeploymentUseCase: Symbol.for("appaloft.retry_deployment_use_case"),
  redeployDeploymentUseCase: Symbol.for("appaloft.redeploy_deployment_use_case"),
  rollbackDeploymentUseCase: Symbol.for("appaloft.rollback_deployment_use_case"),
  cleanupPreviewUseCase: Symbol.for("appaloft.cleanup_preview_use_case"),
  createDomainBindingUseCase: Symbol.for("appaloft.create_domain_binding_use_case"),
  configureDomainBindingRouteUseCase: Symbol.for(
    "appaloft.configure_domain_binding_route_use_case",
  ),
  confirmDomainBindingOwnershipUseCase: Symbol.for(
    "appaloft.confirm_domain_binding_ownership_use_case",
  ),
  deleteDomainBindingUseCase: Symbol.for("appaloft.delete_domain_binding_use_case"),
  retryDomainBindingVerificationUseCase: Symbol.for(
    "appaloft.retry_domain_binding_verification_use_case",
  ),
  listDomainBindingsQueryService: Symbol.for("appaloft.list_domain_bindings_query_service"),
  showDomainBindingQueryService: Symbol.for("appaloft.show_domain_binding_query_service"),
  checkDomainBindingDeleteSafetyQueryService: Symbol.for(
    "appaloft.check_domain_binding_delete_safety_query_service",
  ),
  importCertificateUseCase: Symbol.for("appaloft.import_certificate_use_case"),
  issueOrRenewCertificateUseCase: Symbol.for("appaloft.issue_or_renew_certificate_use_case"),
  retryCertificateUseCase: Symbol.for("appaloft.retry_certificate_use_case"),
  revokeCertificateUseCase: Symbol.for("appaloft.revoke_certificate_use_case"),
  deleteCertificateUseCase: Symbol.for("appaloft.delete_certificate_use_case"),
  certificateRetryScheduler: Symbol.for("appaloft.certificate_retry_scheduler"),
  listCertificatesQueryService: Symbol.for("appaloft.list_certificates_query_service"),
  showCertificateQueryService: Symbol.for("appaloft.show_certificate_query_service"),
  listDeploymentsQueryService: Symbol.for("appaloft.list_deployments_query_service"),
  showDeploymentQueryService: Symbol.for("appaloft.show_deployment_query_service"),
  deploymentPlanQueryService: Symbol.for("appaloft.deployment_plan_query_service"),
  deploymentRecoveryReadinessQueryService: Symbol.for(
    "appaloft.deployment_recovery_readiness_query_service",
  ),
  streamDeploymentEventsQueryService: Symbol.for("appaloft.stream_deployment_events_query_service"),
  logsQueryService: Symbol.for("appaloft.logs_query_service"),
  operatorWorkQueryService: Symbol.for("appaloft.operator_work_query_service"),
  deploymentContextDefaultsFactory: Symbol.for("appaloft.deployment_context_defaults_factory"),
  deploymentContextResolver: Symbol.for("appaloft.deployment_context_resolver"),
  deploymentContextBootstrapService: Symbol.for("appaloft.deployment_context_bootstrap_service"),
  deploymentSnapshotFactory: Symbol.for("appaloft.deployment_snapshot_factory"),
  runtimePlanResolutionInputBuilder: Symbol.for("appaloft.runtime_plan_resolution_input_builder"),
  deploymentFactory: Symbol.for("appaloft.deployment_factory"),
  deploymentLifecycleService: Symbol.for("appaloft.deployment_lifecycle_service"),
  providersQueryService: Symbol.for("appaloft.providers_query_service"),
  pluginsQueryService: Symbol.for("appaloft.plugins_query_service"),
  doctorQueryService: Symbol.for("appaloft.doctor_query_service"),
  dbStatusQueryService: Symbol.for("appaloft.db_status_query_service"),
  dbMigrateUseCase: Symbol.for("appaloft.db_migrate_use_case"),
  sourceDetector: Symbol.for("appaloft.source_detector"),
  runtimePlanResolver: Symbol.for("appaloft.runtime_plan_resolver"),
  deploymentExecutionGuard: Symbol.for("appaloft.deployment_execution_guard"),
  defaultAccessDomainProvider: Symbol.for("appaloft.default_access_domain_provider"),
  edgeProxyProviderRegistry: Symbol.for("appaloft.edge_proxy_provider_registry"),
  runtimeTargetBackendRegistry: Symbol.for("appaloft.runtime_target_backend_registry"),
  executionBackend: Symbol.for("appaloft.execution_backend"),
  resourceRuntimeLogReader: Symbol.for("appaloft.resource_runtime_log_reader"),
  terminalSessionGateway: Symbol.for("appaloft.terminal_session_gateway"),
  providerRegistry: Symbol.for("appaloft.provider_registry"),
  integrationRegistry: Symbol.for("appaloft.integration_registry"),
  integrationAuthPort: Symbol.for("appaloft.integration_auth_port"),
  githubRepositoryBrowser: Symbol.for("appaloft.github_repository_browser"),
  pluginRegistry: Symbol.for("appaloft.plugin_registry"),
  listGitHubRepositoriesQueryService: Symbol.for("appaloft.list_github_repositories_query_service"),
  diagnostics: Symbol.for("appaloft.diagnostics"),
  commandBus: Symbol.for("appaloft.command_bus"),
  queryBus: Symbol.for("appaloft.query_bus"),
} as const;
