export const tokens = {
  clock: Symbol.for("appaloft.clock"),
  idGenerator: Symbol.for("appaloft.id_generator"),
  logger: Symbol.for("appaloft.logger"),
  eventBus: Symbol.for("appaloft.event_bus"),
  operationGuardPort: Symbol.for("appaloft.operation_guard_port"),
  operationAuthorizationPort: Symbol.for("appaloft.operation_guard_port"),
  operationScopePort: Symbol.for("appaloft.operation_scope_port"),
  operationVisibilityPort: Symbol.for("appaloft.operation_scope_port"),
  operationCapabilityPort: Symbol.for("appaloft.operation_capability_port"),
  tenantContextResolver: Symbol.for("appaloft.tenant_context_resolver"),
  entitlementPort: Symbol.for("appaloft.entitlement_port"),
  usageIntentPort: Symbol.for("appaloft.usage_intent_port"),
  deploymentOverlayPort: Symbol.for("appaloft.deployment_overlay_port"),
  routeSurfacePort: Symbol.for("appaloft.route_surface_port"),
  staticArtifactPayloadReaderPort: Symbol.for("appaloft.static_artifact_payload_reader_port"),
  staticArtifactStorePort: Symbol.for("appaloft.static_artifact_store_port"),
  staticArtifactRouteProviderPort: Symbol.for("appaloft.static_artifact_route_provider_port"),
  staticArtifactPublisherPort: Symbol.for("appaloft.static_artifact_publisher_port"),
  staticArtifactPublicationJournalPort: Symbol.for(
    "appaloft.static_artifact_publication_journal_port",
  ),
  staticArtifactPublicationReadModelPort: Symbol.for(
    "appaloft.static_artifact_publication_read_model_port",
  ),
  mutationCoordinator: Symbol.for("appaloft.mutation_coordinator"),
  durableWorkQueueAdapter: Symbol.for("appaloft.durable_work_queue_adapter"),
  durableWorkWorkerHeartbeatStore: Symbol.for("appaloft.durable_work_worker_heartbeat_store"),
  durableWorkHandlerRegistry: Symbol.for("appaloft.durable_work_handler_registry"),
  deploymentProgressRecorder: Symbol.for("appaloft.deployment_progress_recorder"),
  deploymentProgressReporter: Symbol.for("appaloft.deployment_progress_reporter"),
  sourceLinkRepository: Symbol.for("appaloft.source_link_repository"),
  sourceLinkReadModel: Symbol.for("appaloft.source_link_read_model"),
  sourceLinkQueryService: Symbol.for("appaloft.source_link_query_service"),
  defaultAccessDomainPolicyRepository: Symbol.for(
    "appaloft.default_access_domain_policy_repository",
  ),
  defaultAccessDomainPolicySupport: Symbol.for("appaloft.default_access_domain_policy_support"),
  serverConnectivityChecker: Symbol.for("appaloft.server_connectivity_checker"),
  serverRuntimePreparer: Symbol.for("appaloft.server_runtime_preparer"),
  runtimeTargetCapacityInspector: Symbol.for("appaloft.runtime_target_capacity_inspector"),
  storageRuntimeCleaner: Symbol.for("appaloft.storage_runtime_cleaner"),
  runtimeUsageInspector: Symbol.for("appaloft.runtime_usage_inspector"),
  runtimeMonitoringSampleWriteStore: Symbol.for("appaloft.runtime_monitoring_sample_write_store"),
  runtimeMonitoringSampleReadModel: Symbol.for("appaloft.runtime_monitoring_sample_read_model"),
  runtimeMonitoringMarkerReadModel: Symbol.for("appaloft.runtime_monitoring_marker_read_model"),
  runtimeMonitoringSampleRetentionStore: Symbol.for(
    "appaloft.runtime_monitoring_sample_retention_store",
  ),
  runtimeMonitoringThresholdPolicyRepository: Symbol.for(
    "appaloft.runtime_monitoring_threshold_policy_repository",
  ),
  runtimeTargetCapacityPruner: Symbol.for("appaloft.runtime_target_capacity_pruner"),
  serverEdgeProxyBootstrapper: Symbol.for("appaloft.server_edge_proxy_bootstrapper"),
  deploymentConfigReader: Symbol.for("appaloft.deployment_config_reader"),
  sourceVersionDetector: Symbol.for("appaloft.source_version_detector"),
  projectRepository: Symbol.for("appaloft.project_repository"),
  projectDeletionBlockerReader: Symbol.for("appaloft.project_deletion_blocker_reader"),
  serverRepository: Symbol.for("appaloft.server_repository"),
  serverDeletionBlockerReader: Symbol.for("appaloft.server_deletion_blocker_reader"),
  destinationRepository: Symbol.for("appaloft.destination_repository"),
  environmentRepository: Symbol.for("appaloft.environment_repository"),
  resourceRepository: Symbol.for("appaloft.resource_repository"),
  scheduledTaskDefinitionRepository: Symbol.for("appaloft.scheduled_task_definition_repository"),
  scheduledTaskRunAttemptRepository: Symbol.for("appaloft.scheduled_task_run_attempt_repository"),
  scheduledTaskRunLogRecorder: Symbol.for("appaloft.scheduled_task_run_log_recorder"),
  scheduledTaskDueCandidateReader: Symbol.for("appaloft.scheduled_task_due_candidate_reader"),
  dependencyResourceRepository: Symbol.for("appaloft.dependency_resource_repository"),
  dependencyResourceBackupRepository: Symbol.for("appaloft.dependency_resource_backup_repository"),
  dependencyResourceBackupPolicyRepository: Symbol.for(
    "appaloft.dependency_resource_backup_policy_repository",
  ),
  dependencyResourceBackupPolicyReadModel: Symbol.for(
    "appaloft.dependency_resource_backup_policy_read_model",
  ),
  previewEnvironmentRepository: Symbol.for("appaloft.preview_environment_repository"),
  previewPolicyRepository: Symbol.for("appaloft.preview_policy_repository"),
  previewPolicyDecisionRecorder: Symbol.for("appaloft.preview_policy_decision_recorder"),
  previewFeedbackWriter: Symbol.for("appaloft.preview_feedback_writer"),
  previewFeedbackRecorder: Symbol.for("appaloft.preview_feedback_recorder"),
  previewEnvironmentCleaner: Symbol.for("appaloft.preview_environment_cleaner"),
  previewCleanupAttemptRecorder: Symbol.for("appaloft.preview_cleanup_attempt_recorder"),
  previewCleanupRetryCandidateReader: Symbol.for("appaloft.preview_cleanup_retry_candidate_reader"),
  previewExpiredEnvironmentCandidateReader: Symbol.for(
    "appaloft.preview_expired_environment_candidate_reader",
  ),
  resourceDependencyBindingRepository: Symbol.for(
    "appaloft.resource_dependency_binding_repository",
  ),
  deployTokenMaterialIssuer: Symbol.for("appaloft.deploy_token_material_issuer"),
  deployTokenRepository: Symbol.for("appaloft.deploy_token_repository"),
  deployTokenReadModel: Symbol.for("appaloft.deploy_token_read_model"),
  authBootstrapStatusReader: Symbol.for("appaloft.auth_bootstrap_status_reader"),
  firstAdminBootstrapper: Symbol.for("appaloft.first_admin_bootstrapper"),
  firstAdminPasswordIssuer: Symbol.for("appaloft.first_admin_password_issuer"),
  accountSettingsPort: Symbol.for("appaloft.account_settings_port"),
  organizationTeamManagementPort: Symbol.for("appaloft.organization_team_management_port"),
  dependencyResourceDeleteSafetyReader: Symbol.for(
    "appaloft.dependency_resource_delete_safety_reader",
  ),
  storageVolumeRepository: Symbol.for("appaloft.storage_volume_repository"),
  storageVolumeBackupRepository: Symbol.for("appaloft.storage_volume_backup_repository"),
  storageVolumeBackupSafetyReader: Symbol.for("appaloft.storage_volume_backup_safety_reader"),
  storageVolumeBackupProviderRegistry: Symbol.for(
    "appaloft.storage_volume_backup_provider_registry",
  ),
  resourceDeletionBlockerReader: Symbol.for("appaloft.resource_deletion_blocker_reader"),
  deploymentRepository: Symbol.for("appaloft.deployment_repository"),
  domainBindingRepository: Symbol.for("appaloft.domain_binding_repository"),
  domainOwnershipVerifier: Symbol.for("appaloft.domain_ownership_verifier"),
  domainRouteFailureCandidateReader: Symbol.for("appaloft.domain_route_failure_candidate_reader"),
  domainRouteBindingReader: Symbol.for("appaloft.domain_route_binding_reader"),
  serverAppliedRouteStateRepository: Symbol.for("appaloft.server_applied_route_state_repository"),
  certificateRepository: Symbol.for("appaloft.certificate_repository"),
  certificateRetryCandidateReader: Symbol.for("appaloft.certificate_retry_candidate_reader"),
  sshCredentialRepository: Symbol.for("appaloft.ssh_credential_repository"),
  certificateProviderSelectionPolicy: Symbol.for("appaloft.certificate_provider_selection_policy"),
  certificateProvider: Symbol.for("appaloft.certificate_provider"),
  certificateMaterialValidator: Symbol.for("appaloft.certificate_material_validator"),
  certificateSecretStore: Symbol.for("appaloft.certificate_secret_store"),
  dependencyResourceSecretStore: Symbol.for("appaloft.dependency_resource_secret_store"),
  dependencyBindingSecretStore: Symbol.for("appaloft.dependency_binding_secret_store"),
  certificateHttpChallengeTokenStore: Symbol.for("appaloft.certificate_http_challenge_token_store"),
  deploymentContextDefaultsPolicy: Symbol.for("appaloft.deployment_context_defaults_policy"),
  projectOwnershipReadModel: Symbol.for("appaloft.project_ownership_read_model"),
  projectReadModel: Symbol.for("appaloft.project_read_model"),
  serverReadModel: Symbol.for("appaloft.server_read_model"),
  environmentReadModel: Symbol.for("appaloft.environment_read_model"),
  resourceReadModel: Symbol.for("appaloft.resource_read_model"),
  scheduledTaskReadModel: Symbol.for("appaloft.scheduled_task_read_model"),
  scheduledTaskRunReadModel: Symbol.for("appaloft.scheduled_task_run_read_model"),
  scheduledTaskRunLogReadModel: Symbol.for("appaloft.scheduled_task_run_log_read_model"),
  dependencyResourceReadModel: Symbol.for("appaloft.dependency_resource_read_model"),
  dependencyResourceBackupReadModel: Symbol.for("appaloft.dependency_resource_backup_read_model"),
  resourceDependencyBindingReadModel: Symbol.for("appaloft.resource_dependency_binding_read_model"),
  storageVolumeReadModel: Symbol.for("appaloft.storage_volume_read_model"),
  storageVolumeBackupReadModel: Symbol.for("appaloft.storage_volume_backup_read_model"),
  resourceAccessFailureEvidenceRecorder: Symbol.for(
    "appaloft.resource_access_failure_evidence_recorder",
  ),
  resourceAccessFailureEvidenceReadModel: Symbol.for(
    "appaloft.resource_access_failure_evidence_read_model",
  ),
  resourceHealthObservationRecorder: Symbol.for("appaloft.resource_health_observation_recorder"),
  resourceHealthObservationHistoryReadModel: Symbol.for(
    "appaloft.resource_health_observation_history_read_model",
  ),
  sourceEventRecorder: Symbol.for("appaloft.source_event_recorder"),
  sourceEventPolicyReader: Symbol.for("appaloft.source_event_policy_reader"),
  sourceEventDeploymentDispatcher: Symbol.for("appaloft.source_event_deployment_dispatcher"),
  sourceEventReadModel: Symbol.for("appaloft.source_event_read_model"),
  sourceEventRetentionStore: Symbol.for("appaloft.source_event_retention_store"),
  auditEventRecorder: Symbol.for("appaloft.audit_event_recorder"),
  auditEventReadModel: Symbol.for("appaloft.audit_event_read_model"),
  auditEventRetentionStore: Symbol.for("appaloft.audit_event_retention_store"),
  auditEventLegalHoldStore: Symbol.for("appaloft.audit_event_legal_hold_store"),
  auditEventArchiveStore: Symbol.for("appaloft.audit_event_archive_store"),
  providerJobLogRetentionStore: Symbol.for("appaloft.provider_job_log_retention_store"),
  domainEventStreamObservationReader: Symbol.for("appaloft.domain_event_stream_observation_reader"),
  domainEventStreamRecorder: Symbol.for("appaloft.domain_event_stream_recorder"),
  domainEventStreamRetentionStore: Symbol.for("appaloft.domain_event_stream_retention_store"),
  deploymentTimelineObserver: Symbol.for("appaloft.deployment_timeline_observer"),
  deploymentAttemptRetentionStore: Symbol.for("appaloft.deployment_attempt_retention_store"),
  resourceRuntimeControlAttemptRetentionStore: Symbol.for(
    "appaloft.resource_runtime_control_attempt_retention_store",
  ),
  resourceRuntimeLogArchiveStore: Symbol.for("appaloft.resource_runtime_log_archive_store"),
  checkResourceDeleteSafetyQueryService: Symbol.for(
    "appaloft.check_resource_delete_safety_query_service",
  ),
  retentionDefaultRepository: Symbol.for("appaloft.retention_default_repository"),
  previewLifecycleService: Symbol.for("appaloft.preview_lifecycle_service"),
  previewFeedbackService: Symbol.for("appaloft.preview_feedback_service"),
  previewDeploymentProcessManager: Symbol.for("appaloft.preview_deployment_process_manager"),
  previewExpiryCleanupScheduler: Symbol.for("appaloft.preview_expiry_cleanup_scheduler"),
  previewPullRequestEventIngestService: Symbol.for(
    "appaloft.preview_pull_request_event_ingest_service",
  ),
  previewEnvironmentReadModel: Symbol.for("appaloft.preview_environment_read_model"),
  previewPolicyReadModel: Symbol.for("appaloft.preview_policy_read_model"),
  previewPolicyDecisionReadModel: Symbol.for("appaloft.preview_policy_decision_read_model"),
  deploymentReadModel: Symbol.for("appaloft.deployment_read_model"),
  domainBindingReadModel: Symbol.for("appaloft.domain_binding_read_model"),
  certificateReadModel: Symbol.for("appaloft.certificate_read_model"),
  processAttemptRecorder: Symbol.for("appaloft.process_attempt_recorder"),
  processAttemptRecoveryRecorder: Symbol.for("appaloft.process_attempt_recovery_recorder"),
  processAttemptReadModel: Symbol.for("appaloft.process_attempt_read_model"),
  processAttemptRetryCandidateReader: Symbol.for("appaloft.process_attempt_retry_candidate_reader"),
  processAttemptDeliveryCandidateReader: Symbol.for(
    "appaloft.process_attempt_delivery_candidate_reader",
  ),
  processAttemptRetryGenerator: Symbol.for("appaloft.process_attempt_retry_generator"),
  processAttemptClaimer: Symbol.for("appaloft.process_attempt_claimer"),
  processAttemptCompleter: Symbol.for("appaloft.process_attempt_completer"),
  remoteStateWorkReadModel: Symbol.for("appaloft.remote_state_work_read_model"),
  routeRealizationWorkReadModel: Symbol.for("appaloft.route_realization_work_read_model"),
  sshCredentialReadModel: Symbol.for("appaloft.ssh_credential_read_model"),
  sshCredentialUsageReader: Symbol.for("appaloft.ssh_credential_usage_reader"),
  archiveProjectUseCase: Symbol.for("appaloft.archive_project_use_case"),
  createProjectUseCase: Symbol.for("appaloft.create_project_use_case"),
  createDeployTokenUseCase: Symbol.for("appaloft.create_deploy_token_use_case"),
  bootstrapFirstAdminUseCase: Symbol.for("appaloft.bootstrap_first_admin_use_case"),
  getAuthBootstrapStatusQueryService: Symbol.for(
    "appaloft.get_auth_bootstrap_status_query_service",
  ),
  getCurrentOrganizationContextQueryService: Symbol.for(
    "appaloft.get_current_organization_context_query_service",
  ),
  deleteAccountUseCase: Symbol.for("appaloft.delete_account_use_case"),
  listAccountSessionsQueryService: Symbol.for("appaloft.list_account_sessions_query_service"),
  revokeAccountSessionUseCase: Symbol.for("appaloft.revoke_account_session_use_case"),
  showAccountProfileQueryService: Symbol.for("appaloft.show_account_profile_query_service"),
  changeAccountProfileUseCase: Symbol.for("appaloft.change_account_profile_use_case"),
  deleteOrganizationUseCase: Symbol.for("appaloft.delete_organization_use_case"),
  showOrganizationProfileQueryService: Symbol.for(
    "appaloft.show_organization_profile_query_service",
  ),
  changeOrganizationProfileUseCase: Symbol.for("appaloft.change_organization_profile_use_case"),
  inviteOrganizationMemberUseCase: Symbol.for("appaloft.invite_organization_member_use_case"),
  switchCurrentOrganizationUseCase: Symbol.for("appaloft.switch_current_organization_use_case"),
  listDeployTokensQueryService: Symbol.for("appaloft.list_deploy_tokens_query_service"),
  pruneAuditEventsUseCase: Symbol.for("appaloft.prune_audit_events_use_case"),
  exportAuditEventsQueryService: Symbol.for("appaloft.export_audit_events_query_service"),
  exportGlobalAuditEventsQueryService: Symbol.for(
    "appaloft.export_global_audit_events_query_service",
  ),
  pruneProviderJobLogsUseCase: Symbol.for("appaloft.prune_provider_job_logs_use_case"),
  pruneDomainEventsUseCase: Symbol.for("appaloft.prune_domain_events_use_case"),
  configureRetentionDefaultsUseCase: Symbol.for("appaloft.configure_retention_defaults_use_case"),
  listRetentionDefaultsQueryService: Symbol.for("appaloft.list_retention_defaults_query_service"),
  showRetentionDefaultQueryService: Symbol.for("appaloft.show_retention_default_query_service"),
  scheduledHistoryRetentionService: Symbol.for("appaloft.scheduled_history_retention_service"),
  listOrganizationInvitationsQueryService: Symbol.for(
    "appaloft.list_organization_invitations_query_service",
  ),
  listOrganizationMembersQueryService: Symbol.for(
    "appaloft.list_organization_members_query_service",
  ),
  removeOrganizationMemberUseCase: Symbol.for("appaloft.remove_organization_member_use_case"),
  reactivateOrganizationMemberUseCase: Symbol.for(
    "appaloft.reactivate_organization_member_use_case",
  ),
  revokeDeployTokenUseCase: Symbol.for("appaloft.revoke_deploy_token_use_case"),
  rotateDeployTokenUseCase: Symbol.for("appaloft.rotate_deploy_token_use_case"),
  showDeployTokenQueryService: Symbol.for("appaloft.show_deploy_token_query_service"),
  changeOrganizationMemberRoleUseCase: Symbol.for(
    "appaloft.change_organization_member_role_use_case",
  ),
  transferOrganizationOwnerUseCase: Symbol.for("appaloft.transfer_organization_owner_use_case"),
  countProjectsQueryService: Symbol.for("appaloft.count_projects_query_service"),
  listProjectsQueryService: Symbol.for("appaloft.list_projects_query_service"),
  queryCapabilitiesQueryService: Symbol.for("appaloft.query_capabilities_query_service"),
  queryEntitlementsQueryService: Symbol.for("appaloft.query_entitlements_query_service"),
  recordUsageIntentUseCase: Symbol.for("appaloft.record_usage_intent_use_case"),
  listUsageIntentRecordsQueryService: Symbol.for(
    "appaloft.list_usage_intent_records_query_service",
  ),
  evaluateDeploymentOverlayUseCase: Symbol.for("appaloft.evaluate_deployment_overlay_use_case"),
  listDeploymentOverlayDecisionsQueryService: Symbol.for(
    "appaloft.list_deployment_overlay_decisions_query_service",
  ),
  evaluateRouteSurfaceUseCase: Symbol.for("appaloft.evaluate_route_surface_use_case"),
  listRouteSurfaceDecisionsQueryService: Symbol.for(
    "appaloft.list_route_surface_decisions_query_service",
  ),
  checkProjectDeleteSafetyQueryService: Symbol.for(
    "appaloft.check_project_delete_safety_query_service",
  ),
  deleteProjectUseCase: Symbol.for("appaloft.delete_project_use_case"),
  renameProjectUseCase: Symbol.for("appaloft.rename_project_use_case"),
  reorderProjectsUseCase: Symbol.for("appaloft.reorder_projects_use_case"),
  restoreProjectUseCase: Symbol.for("appaloft.restore_project_use_case"),
  setProjectDescriptionUseCase: Symbol.for("appaloft.set_project_description_use_case"),
  showProjectQueryService: Symbol.for("appaloft.show_project_query_service"),
  configureDefaultAccessDomainPolicyUseCase: Symbol.for(
    "appaloft.configure_default_access_domain_policy_use_case",
  ),
  listDefaultAccessDomainPoliciesQueryService: Symbol.for(
    "appaloft.list_default_access_domain_policies_query_service",
  ),
  showDefaultAccessDomainPolicyQueryService: Symbol.for(
    "appaloft.show_default_access_domain_policy_query_service",
  ),
  registerServerUseCase: Symbol.for("appaloft.register_server_use_case"),
  configureServerCredentialUseCase: Symbol.for("appaloft.configure_server_credential_use_case"),
  createSshCredentialUseCase: Symbol.for("appaloft.create_ssh_credential_use_case"),
  countServersQueryService: Symbol.for("appaloft.count_servers_query_service"),
  reorderServersUseCase: Symbol.for("appaloft.reorder_servers_use_case"),
  listSshCredentialsQueryService: Symbol.for("appaloft.list_ssh_credentials_query_service"),
  showSshCredentialQueryService: Symbol.for("appaloft.show_ssh_credential_query_service"),
  listServersQueryService: Symbol.for("appaloft.list_servers_query_service"),
  showServerQueryService: Symbol.for("appaloft.show_server_query_service"),
  inspectServerCapacityQueryService: Symbol.for("appaloft.inspect_server_capacity_query_service"),
  runtimeUsageInspectionQueryService: Symbol.for("appaloft.runtime_usage_inspection_query_service"),
  listRuntimeMonitoringSamplesQueryService: Symbol.for(
    "appaloft.list_runtime_monitoring_samples_query_service",
  ),
  runtimeMonitoringRollupQueryService: Symbol.for(
    "appaloft.runtime_monitoring_rollup_query_service",
  ),
  configureRuntimeMonitoringThresholdsUseCase: Symbol.for(
    "appaloft.configure_runtime_monitoring_thresholds_use_case",
  ),
  showRuntimeMonitoringThresholdsQueryService: Symbol.for(
    "appaloft.show_runtime_monitoring_thresholds_query_service",
  ),
  runtimeMonitoringCollectorService: Symbol.for("appaloft.runtime_monitoring_collector_service"),
  pruneServerCapacityUseCase: Symbol.for("appaloft.prune_server_capacity_use_case"),
  scheduledRuntimePrunePolicyRepository: Symbol.for(
    "appaloft.scheduled_runtime_prune_policy_repository",
  ),
  scheduledRuntimePrunePolicyReadModel: Symbol.for(
    "appaloft.scheduled_runtime_prune_policy_read_model",
  ),
  configureScheduledRuntimePrunePolicyUseCase: Symbol.for(
    "appaloft.configure_scheduled_runtime_prune_policy_use_case",
  ),
  showScheduledRuntimePrunePolicyQueryService: Symbol.for(
    "appaloft.show_scheduled_runtime_prune_policy_query_service",
  ),
  listScheduledRuntimePrunePoliciesQueryService: Symbol.for(
    "appaloft.list_scheduled_runtime_prune_policies_query_service",
  ),
  scheduledRuntimePrunePolicyResolver: Symbol.for(
    "appaloft.scheduled_runtime_prune_policy_resolver",
  ),
  scheduledRuntimePruneService: Symbol.for("appaloft.scheduled_runtime_prune_service"),
  renameServerUseCase: Symbol.for("appaloft.rename_server_use_case"),
  configureServerEdgeProxyUseCase: Symbol.for("appaloft.configure_server_edge_proxy_use_case"),
  deactivateServerUseCase: Symbol.for("appaloft.deactivate_server_use_case"),
  deleteServerUseCase: Symbol.for("appaloft.delete_server_use_case"),
  deleteSshCredentialUseCase: Symbol.for("appaloft.delete_ssh_credential_use_case"),
  rotateSshCredentialUseCase: Symbol.for("appaloft.rotate_ssh_credential_use_case"),
  checkServerDeleteSafetyQueryService: Symbol.for(
    "appaloft.check_server_delete_safety_query_service",
  ),
  testServerConnectivityUseCase: Symbol.for("appaloft.test_server_connectivity_use_case"),
  prepareServerRuntimeUseCase: Symbol.for("appaloft.prepare_server_runtime_use_case"),
  bootstrapServerProxyUseCase: Symbol.for("appaloft.bootstrap_server_proxy_use_case"),
  archiveEnvironmentUseCase: Symbol.for("appaloft.archive_environment_use_case"),
  cloneEnvironmentUseCase: Symbol.for("appaloft.clone_environment_use_case"),
  countEnvironmentsQueryService: Symbol.for("appaloft.count_environments_query_service"),
  renameEnvironmentUseCase: Symbol.for("appaloft.rename_environment_use_case"),
  lockEnvironmentUseCase: Symbol.for("appaloft.lock_environment_use_case"),
  unlockEnvironmentUseCase: Symbol.for("appaloft.unlock_environment_use_case"),
  createEnvironmentUseCase: Symbol.for("appaloft.create_environment_use_case"),
  listEnvironmentsQueryService: Symbol.for("appaloft.list_environments_query_service"),
  showEnvironmentQueryService: Symbol.for("appaloft.show_environment_query_service"),
  environmentEffectivePrecedenceQueryService: Symbol.for(
    "appaloft.environment_effective_precedence_query_service",
  ),
  createResourceUseCase: Symbol.for("appaloft.create_resource_use_case"),
  archiveResourceUseCase: Symbol.for("appaloft.archive_resource_use_case"),
  restoreResourceUseCase: Symbol.for("appaloft.restore_resource_use_case"),
  deleteResourceUseCase: Symbol.for("appaloft.delete_resource_use_case"),
  configureResourceAutoDeployUseCase: Symbol.for(
    "appaloft.configure_resource_auto_deploy_use_case",
  ),
  configureResourceSourceUseCase: Symbol.for("appaloft.configure_resource_source_use_case"),
  configureResourceAccessUseCase: Symbol.for("appaloft.configure_resource_access_use_case"),
  configureResourceHealthUseCase: Symbol.for("appaloft.configure_resource_health_use_case"),
  resetResourceHealthUseCase: Symbol.for("appaloft.reset_resource_health_use_case"),
  configureResourceNetworkUseCase: Symbol.for("appaloft.configure_resource_network_use_case"),
  configureResourceRuntimeUseCase: Symbol.for("appaloft.configure_resource_runtime_use_case"),
  createResourceSecretReferenceUseCase: Symbol.for(
    "appaloft.create_resource_secret_reference_use_case",
  ),
  rotateResourceSecretReferenceUseCase: Symbol.for(
    "appaloft.update_resource_secret_reference_use_case",
  ),
  deleteResourceSecretReferenceUseCase: Symbol.for(
    "appaloft.delete_resource_secret_reference_use_case",
  ),
  importResourceVariablesUseCase: Symbol.for("appaloft.import_resource_variables_use_case"),
  setResourceVariableUseCase: Symbol.for("appaloft.set_resource_variable_use_case"),
  unsetResourceVariableUseCase: Symbol.for("appaloft.unset_resource_variable_use_case"),
  attachResourceStorageUseCase: Symbol.for("appaloft.attach_resource_storage_use_case"),
  detachResourceStorageUseCase: Symbol.for("appaloft.detach_resource_storage_use_case"),
  bindResourceDependencyUseCase: Symbol.for("appaloft.bind_resource_dependency_use_case"),
  unbindResourceDependencyUseCase: Symbol.for("appaloft.unbind_resource_dependency_use_case"),
  rotateResourceDependencyBindingSecretUseCase: Symbol.for(
    "appaloft.rotate_resource_dependency_binding_secret_use_case",
  ),
  configureDependencyResourceBackupPolicyUseCase: Symbol.for(
    "appaloft.configure_dependency_resource_backup_policy_use_case",
  ),
  listDependencyResourceBackupPoliciesQueryService: Symbol.for(
    "appaloft.list_dependency_resource_backup_policies_query_service",
  ),
  showDependencyResourceBackupPolicyQueryService: Symbol.for(
    "appaloft.show_dependency_resource_backup_policy_query_service",
  ),
  scheduledDependencyBackupService: Symbol.for("appaloft.scheduled_dependency_backup_service"),
  dependencyResourceProvisioningPlanStore: Symbol.for(
    "appaloft.dependency_resource_provisioning_plan_store",
  ),
  createDependencyResourceProvisioningPlanUseCase: Symbol.for(
    "appaloft.create_dependency_resource_provisioning_plan_use_case",
  ),
  acceptDependencyResourceProvisioningPlanUseCase: Symbol.for(
    "appaloft.accept_dependency_resource_provisioning_plan_use_case",
  ),
  showDependencyResourceProvisioningPlanQueryService: Symbol.for(
    "appaloft.show_dependency_resource_provisioning_plan_query_service",
  ),
  countResourcesQueryService: Symbol.for("appaloft.count_resources_query_service"),
  listResourcesQueryService: Symbol.for("appaloft.list_resources_query_service"),
  showResourceQueryService: Symbol.for("appaloft.show_resource_query_service"),
  listResourceDependencyBindingsQueryService: Symbol.for(
    "appaloft.list_resource_dependency_bindings_query_service",
  ),
  showResourceDependencyBindingQueryService: Symbol.for(
    "appaloft.show_resource_dependency_binding_query_service",
  ),
  provisionDependencyResourceUseCase: Symbol.for("appaloft.provision_dependency_resource_use_case"),
  importDependencyResourceUseCase: Symbol.for("appaloft.import_dependency_resource_use_case"),
  renameDependencyResourceUseCase: Symbol.for("appaloft.rename_dependency_resource_use_case"),
  deleteDependencyResourceUseCase: Symbol.for("appaloft.delete_dependency_resource_use_case"),
  managedDependencyProvider: Symbol.for("appaloft.managed_dependency_provider"),
  dependencyResourceBackupProvider: Symbol.for("appaloft.dependency_resource_backup_provider"),
  createDependencyResourceBackupUseCase: Symbol.for(
    "appaloft.create_dependency_resource_backup_use_case",
  ),
  restoreDependencyResourceBackupUseCase: Symbol.for(
    "appaloft.restore_dependency_resource_backup_use_case",
  ),
  countDependencyResourcesQueryService: Symbol.for(
    "appaloft.count_dependency_resources_query_service",
  ),
  listDependencyResourcesQueryService: Symbol.for(
    "appaloft.list_dependency_resources_query_service",
  ),
  showDependencyResourceQueryService: Symbol.for("appaloft.show_dependency_resource_query_service"),
  listDependencyResourceBackupsQueryService: Symbol.for(
    "appaloft.list_dependency_resource_backups_query_service",
  ),
  showDependencyResourceBackupQueryService: Symbol.for(
    "appaloft.show_dependency_resource_backup_query_service",
  ),
  createStorageVolumeUseCase: Symbol.for("appaloft.create_storage_volume_use_case"),
  renameStorageVolumeUseCase: Symbol.for("appaloft.rename_storage_volume_use_case"),
  deleteStorageVolumeUseCase: Symbol.for("appaloft.delete_storage_volume_use_case"),
  cleanupStorageVolumeRuntimeUseCase: Symbol.for(
    "appaloft.cleanup_storage_volume_runtime_use_case",
  ),
  createStorageVolumeBackupUseCase: Symbol.for("appaloft.create_storage_volume_backup_use_case"),
  restoreStorageVolumeBackupUseCase: Symbol.for("appaloft.restore_storage_volume_backup_use_case"),
  pruneStorageVolumeBackupUseCase: Symbol.for("appaloft.prune_storage_volume_backup_use_case"),
  listStorageVolumesQueryService: Symbol.for("appaloft.list_storage_volumes_query_service"),
  showStorageVolumeQueryService: Symbol.for("appaloft.show_storage_volume_query_service"),
  createStorageVolumeBackupPlanQueryService: Symbol.for(
    "appaloft.create_storage_volume_backup_plan_query_service",
  ),
  listStorageVolumeBackupsQueryService: Symbol.for(
    "appaloft.list_storage_volume_backups_query_service",
  ),
  showStorageVolumeBackupQueryService: Symbol.for(
    "appaloft.show_storage_volume_backup_query_service",
  ),
  createStorageVolumeRestorePlanQueryService: Symbol.for(
    "appaloft.create_storage_volume_restore_plan_query_service",
  ),
  resourceEffectiveConfigQueryService: Symbol.for(
    "appaloft.resource_effective_config_query_service",
  ),
  resourceSecretReferenceQueryService: Symbol.for(
    "appaloft.resource_secret_reference_query_service",
  ),
  resourceDiagnosticSummaryQueryService: Symbol.for(
    "appaloft.resource_diagnostic_summary_query_service",
  ),
  resourceAccessFailureEvidenceLookupQueryService: Symbol.for(
    "appaloft.resource_access_failure_evidence_lookup_query_service",
  ),
  automaticRouteContextLookupService: Symbol.for("appaloft.automatic_route_context_lookup_service"),
  resourceHealthQueryService: Symbol.for("appaloft.resource_health_query_service"),
  resourceHealthHistoryQueryService: Symbol.for("appaloft.resource_health_history_query_service"),
  resourceHealthProbeRunner: Symbol.for("appaloft.resource_health_probe_runner"),
  resourceRuntimeLogsQueryService: Symbol.for("appaloft.resource_runtime_logs_query_service"),
  archiveResourceRuntimeLogsUseCase: Symbol.for("appaloft.archive_resource_runtime_logs_use_case"),
  listResourceRuntimeLogArchivesQueryService: Symbol.for(
    "appaloft.list_resource_runtime_log_archives_query_service",
  ),
  showResourceRuntimeLogArchiveQueryService: Symbol.for(
    "appaloft.show_resource_runtime_log_archive_query_service",
  ),
  pruneResourceRuntimeLogArchivesUseCase: Symbol.for(
    "appaloft.prune_resource_runtime_log_archives_use_case",
  ),
  resourceRuntimeControlUseCase: Symbol.for("appaloft.resource_runtime_control_use_case"),
  resourceRuntimeControlTargetPort: Symbol.for("appaloft.resource_runtime_control_target_port"),
  resourceRuntimeControlAttemptRecorder: Symbol.for(
    "appaloft.resource_runtime_control_attempt_recorder",
  ),
  createScheduledTaskUseCase: Symbol.for("appaloft.create_scheduled_task_use_case"),
  configureScheduledTaskUseCase: Symbol.for("appaloft.configure_scheduled_task_use_case"),
  deleteScheduledTaskUseCase: Symbol.for("appaloft.delete_scheduled_task_use_case"),
  listScheduledTasksQueryService: Symbol.for("appaloft.list_scheduled_tasks_query_service"),
  showScheduledTaskQueryService: Symbol.for("appaloft.show_scheduled_task_query_service"),
  listScheduledTaskRunsQueryService: Symbol.for("appaloft.list_scheduled_task_runs_query_service"),
  showScheduledTaskRunQueryService: Symbol.for("appaloft.show_scheduled_task_run_query_service"),
  scheduledTaskRunLogsQueryService: Symbol.for("appaloft.scheduled_task_run_logs_query_service"),
  scheduledTaskRunAdmissionService: Symbol.for("appaloft.scheduled_task_run_admission_service"),
  scheduledTaskRunWorker: Symbol.for("appaloft.scheduled_task_run_worker"),
  scheduledTaskRuntimePort: Symbol.for("appaloft.scheduled_task_runtime_port"),
  runScheduledTaskNowUseCase: Symbol.for("appaloft.run_scheduled_task_now_use_case"),
  scheduledTaskScheduler: Symbol.for("appaloft.scheduled_task_scheduler"),
  ingestSourceEventUseCase: Symbol.for("appaloft.ingest_source_event_use_case"),
  pruneSourceEventsUseCase: Symbol.for("appaloft.prune_source_events_use_case"),
  replaySourceEventUseCase: Symbol.for("appaloft.replay_source_event_use_case"),
  sourceEventVerificationPort: Symbol.for("appaloft.source_event_verification_port"),
  githubSourceEventWebhookVerifier: Symbol.for("appaloft.github_source_event_webhook_verifier"),
  githubPreviewPullRequestWebhookVerifier: Symbol.for(
    "appaloft.github_preview_pull_request_webhook_verifier",
  ),
  listSourceEventsQueryService: Symbol.for("appaloft.list_source_events_query_service"),
  showSourceEventQueryService: Symbol.for("appaloft.show_source_event_query_service"),
  listAuditEventsQueryService: Symbol.for("appaloft.list_audit_events_query_service"),
  showAuditEventQueryService: Symbol.for("appaloft.show_audit_event_query_service"),
  configureAuditEventLegalHoldUseCase: Symbol.for(
    "appaloft.configure_audit_event_legal_hold_use_case",
  ),
  releaseAuditEventLegalHoldUseCase: Symbol.for("appaloft.release_audit_event_legal_hold_use_case"),
  listAuditEventLegalHoldsQueryService: Symbol.for(
    "appaloft.list_audit_event_legal_holds_query_service",
  ),
  showAuditEventLegalHoldQueryService: Symbol.for(
    "appaloft.show_audit_event_legal_hold_query_service",
  ),
  createAuditEventArchiveUseCase: Symbol.for("appaloft.create_audit_event_archive_use_case"),
  pruneAuditEventArchivesUseCase: Symbol.for("appaloft.prune_audit_event_archives_use_case"),
  listAuditEventArchivesQueryService: Symbol.for(
    "appaloft.list_audit_event_archives_query_service",
  ),
  showAuditEventArchiveQueryService: Symbol.for("appaloft.show_audit_event_archive_query_service"),
  resolveGenericSignedSourceEventSecretQueryService: Symbol.for(
    "appaloft.resolve_generic_signed_source_event_secret_query_service",
  ),
  resolvePreviewPullRequestContextQueryService: Symbol.for(
    "appaloft.resolve_preview_pull_request_context_query_service",
  ),
  configurePreviewPolicyUseCase: Symbol.for("appaloft.configure_preview_policy_use_case"),
  showPreviewPolicyQueryService: Symbol.for("appaloft.show_preview_policy_query_service"),
  listPreviewEnvironmentsQueryService: Symbol.for(
    "appaloft.list_preview_environments_query_service",
  ),
  showPreviewEnvironmentQueryService: Symbol.for("appaloft.show_preview_environment_query_service"),
  previewEnvironmentCleanupService: Symbol.for("appaloft.preview_environment_cleanup_service"),
  previewCleanupRetryScheduler: Symbol.for("appaloft.preview_cleanup_retry_scheduler"),
  openTerminalSessionUseCase: Symbol.for("appaloft.open_terminal_session_use_case"),
  terminalSessionLifecycleService: Symbol.for("appaloft.terminal_session_lifecycle_service"),
  deleteSourceLinkUseCase: Symbol.for("appaloft.delete_source_link_use_case"),
  relinkSourceLinkUseCase: Symbol.for("appaloft.relink_source_link_use_case"),
  resourceProxyConfigurationPreviewQueryService: Symbol.for(
    "appaloft.resource_proxy_configuration_preview_query_service",
  ),
  setEnvironmentVariableUseCase: Symbol.for("appaloft.set_environment_variable_use_case"),
  unsetEnvironmentVariableUseCase: Symbol.for("appaloft.unset_environment_variable_use_case"),
  diffEnvironmentsQueryService: Symbol.for("appaloft.diff_environments_query_service"),
  promoteEnvironmentUseCase: Symbol.for("appaloft.promote_environment_use_case"),
  applyActionPreviewRouteUseCase: Symbol.for("appaloft.apply_action_preview_route_use_case"),
  confirmActionPreviewRouteUseCase: Symbol.for("appaloft.confirm_action_preview_route_use_case"),
  createActionSourceLinkDeploymentUseCase: Symbol.for(
    "appaloft.create_action_source_link_deployment_use_case",
  ),
  resolveActionServerConfigDeploymentTargetUseCase: Symbol.for(
    "appaloft.resolve_action_server_config_deployment_target_use_case",
  ),
  createDeploymentUseCase: Symbol.for("appaloft.create_deployment_use_case"),
  retryDeploymentUseCase: Symbol.for("appaloft.retry_deployment_use_case"),
  redeployDeploymentUseCase: Symbol.for("appaloft.redeploy_deployment_use_case"),
  rollbackDeploymentUseCase: Symbol.for("appaloft.rollback_deployment_use_case"),
  cancelDeploymentUseCase: Symbol.for("appaloft.cancel_deployment_use_case"),
  archiveDeploymentUseCase: Symbol.for("appaloft.archive_deployment_use_case"),
  pruneDeploymentsUseCase: Symbol.for("appaloft.prune_deployments_use_case"),
  pruneResourceRuntimeControlAttemptsUseCase: Symbol.for(
    "appaloft.prune_resource_runtime_control_attempts_use_case",
  ),
  cleanupPreviewUseCase: Symbol.for("appaloft.cleanup_preview_use_case"),
  createDomainBindingUseCase: Symbol.for("appaloft.create_domain_binding_use_case"),
  configureDomainBindingRouteUseCase: Symbol.for(
    "appaloft.configure_domain_binding_route_use_case",
  ),
  confirmDomainBindingOwnershipUseCase: Symbol.for(
    "appaloft.confirm_domain_binding_ownership_use_case",
  ),
  deleteDomainBindingUseCase: Symbol.for("appaloft.delete_domain_binding_use_case"),
  retryDomainBindingVerificationUseCase: Symbol.for(
    "appaloft.retry_domain_binding_verification_use_case",
  ),
  listDomainBindingsQueryService: Symbol.for("appaloft.list_domain_bindings_query_service"),
  showDomainBindingQueryService: Symbol.for("appaloft.show_domain_binding_query_service"),
  checkDomainBindingDeleteSafetyQueryService: Symbol.for(
    "appaloft.check_domain_binding_delete_safety_query_service",
  ),
  importCertificateUseCase: Symbol.for("appaloft.import_certificate_use_case"),
  issueOrRenewCertificateUseCase: Symbol.for("appaloft.issue_or_renew_certificate_use_case"),
  retryCertificateUseCase: Symbol.for("appaloft.retry_certificate_use_case"),
  revokeCertificateUseCase: Symbol.for("appaloft.revoke_certificate_use_case"),
  deleteCertificateUseCase: Symbol.for("appaloft.delete_certificate_use_case"),
  certificateRetryScheduler: Symbol.for("appaloft.certificate_retry_scheduler"),
  listCertificatesQueryService: Symbol.for("appaloft.list_certificates_query_service"),
  showCertificateQueryService: Symbol.for("appaloft.show_certificate_query_service"),
  countDeploymentsQueryService: Symbol.for("appaloft.count_deployments_query_service"),
  listDeploymentsQueryService: Symbol.for("appaloft.list_deployments_query_service"),
  showDeploymentQueryService: Symbol.for("appaloft.show_deployment_query_service"),
  deploymentPlanQueryService: Symbol.for("appaloft.deployment_plan_query_service"),
  deploymentRecoveryReadinessQueryService: Symbol.for(
    "appaloft.deployment_recovery_readiness_query_service",
  ),
  deploymentTimelineQueryService: Symbol.for("appaloft.deployment_timeline_query_service"),
  operatorWorkQueryService: Symbol.for("appaloft.operator_work_query_service"),
  streamOperatorWorkEventsQueryService: Symbol.for(
    "appaloft.stream_operator_work_events_query_service",
  ),
  cancelOperatorWorkUseCase: Symbol.for("appaloft.cancel_operator_work_use_case"),
  deadLetterOperatorWorkUseCase: Symbol.for("appaloft.dead_letter_operator_work_use_case"),
  markOperatorWorkRecoveredUseCase: Symbol.for("appaloft.mark_operator_work_recovered_use_case"),
  pruneOperatorWorkUseCase: Symbol.for("appaloft.prune_operator_work_use_case"),
  retryOperatorWorkUseCase: Symbol.for("appaloft.retry_operator_work_use_case"),
  deploymentContextDefaultsFactory: Symbol.for("appaloft.deployment_context_defaults_factory"),
  deploymentContextResolver: Symbol.for("appaloft.deployment_context_resolver"),
  deploymentContextBootstrapService: Symbol.for("appaloft.deployment_context_bootstrap_service"),
  deploymentSnapshotFactory: Symbol.for("appaloft.deployment_snapshot_factory"),
  runtimePlanResolutionInputBuilder: Symbol.for("appaloft.runtime_plan_resolution_input_builder"),
  deploymentFactory: Symbol.for("appaloft.deployment_factory"),
  deploymentLifecycleService: Symbol.for("appaloft.deployment_lifecycle_service"),
  providersQueryService: Symbol.for("appaloft.providers_query_service"),
  connectorsQueryService: Symbol.for("appaloft.connectors_query_service"),
  connectorCategoriesQueryService: Symbol.for("appaloft.connector_categories_query_service"),
  integrationsQueryService: Symbol.for("appaloft.integrations_query_service"),
  pluginsQueryService: Symbol.for("appaloft.plugins_query_service"),
  doctorQueryService: Symbol.for("appaloft.doctor_query_service"),
  maintenanceWorkerStatusReader: Symbol.for("appaloft.maintenance_worker_status_reader"),
  dbStatusQueryService: Symbol.for("appaloft.db_status_query_service"),
  dbMigrateUseCase: Symbol.for("appaloft.db_migrate_use_case"),
  instanceUpgrade: Symbol.for("appaloft.instance_upgrade"),
  checkInstanceUpgradeQueryService: Symbol.for("appaloft.check_instance_upgrade_query_service"),
  applyInstanceUpgradeUseCase: Symbol.for("appaloft.apply_instance_upgrade_use_case"),
  sourceDetector: Symbol.for("appaloft.source_detector"),
  runtimePlanResolver: Symbol.for("appaloft.runtime_plan_resolver"),
  deploymentExecutionGuard: Symbol.for("appaloft.deployment_execution_guard"),
  defaultAccessDomainProvider: Symbol.for("appaloft.default_access_domain_provider"),
  edgeProxyProviderRegistry: Symbol.for("appaloft.edge_proxy_provider_registry"),
  runtimeTargetBackendRegistry: Symbol.for("appaloft.runtime_target_backend_registry"),
  executionBackend: Symbol.for("appaloft.execution_backend"),
  resourceRuntimeLogReader: Symbol.for("appaloft.resource_runtime_log_reader"),
  terminalSessionGateway: Symbol.for("appaloft.terminal_session_gateway"),
  providerRegistry: Symbol.for("appaloft.provider_registry"),
  connectorRegistry: Symbol.for("appaloft.connector_registry"),
  connectorProviderAdapterRegistry: Symbol.for("appaloft.connector_provider_adapter_registry"),
  integrationRegistry: Symbol.for("appaloft.integration_registry"),
  blueprintRegistry: Symbol.for("appaloft.blueprint_registry"),
  blueprintCatalogQueryService: Symbol.for("appaloft.blueprint_catalog_query_service"),
  blueprintInstallCommandService: Symbol.for("appaloft.blueprint_install_command_service"),
  blueprintInstallationQueryService: Symbol.for("appaloft.blueprint_installation_query_service"),
  integrationAuthPort: Symbol.for("appaloft.integration_auth_port"),
  githubAppInstallationRepository: Symbol.for("appaloft.github_app_installation_repository"),
  githubAppRuntime: Symbol.for("appaloft.github_app_runtime"),
  githubAppConnectionQueryService: Symbol.for("appaloft.github_app_connection_query_service"),
  upsertGitHubAppInstallationUseCase: Symbol.for(
    "appaloft.upsert_github_app_installation_use_case",
  ),
  githubRepositoryBrowser: Symbol.for("appaloft.github_repository_browser"),
  pluginRegistry: Symbol.for("appaloft.plugin_registry"),
  listGitHubRepositoriesQueryService: Symbol.for("appaloft.list_github_repositories_query_service"),
  diagnostics: Symbol.for("appaloft.diagnostics"),
  commandBus: Symbol.for("appaloft.command_bus"),
  queryBus: Symbol.for("appaloft.query_bus"),
} as const;
